export const SET_INDUSTRY = "SET_INDUSTRY";

export const CHANGE_LAYOUT = "CHANGE_LAYOUT";
export const TOGGLE_BOXED_LAYOUT = "TOGGLE_BOXED_LAYOUT";
export const TOGGLE_COLLAPSED_NAV = "TOGGLE_COLLAPSED_NAV";
export const TOGGLE_OFFCANVAS_NAV = "TOGGLE_OFFCANVAS_NAV";
export const TOGGLE_FIXED_SIDENAV = "TOGGLE_FIXED_SIDENAV";
export const TOGGLE_FIXED_HEADER = "TOGGLE_FIXED_HEADER";
export const CHANGE_SIDENAV_WIDTH = "CHANGE_SIDENAV_WIDTH";
export const TOGGLE_OFFCANVAS_MOBILE_NAV = "TOGGLE_OFFCANVAS_MOBILE_NAV";
export const CHANGE_COLOR_OPTION = "CHANGE_COLOR_OPTION";
export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_WINDOW_SIZES = "CHANGE_WINDOW_SIZES";
export const SET_HEADER_DATA = "SET_HEADER_DATA";
export const SET_SETTING_GROUP_KEY = "SET_SETTING_GROUP_KEY";
export const SET_CART_ITEMS_COUNT = "SET_CART_ITEMS_COUNT";
export const SET_MOVE_POS_PAGE_ACTION = "SET_MOVE_POS_PAGE_ACTION";
export const SET_LOG_OUT_CHECK_ACTION = "SET_LOG_OUT_CHECK_ACTION";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_SET_AUTHORIZED_HEADER = "AUTH_SET_AUTHORIZED_HEADER";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const CHECK_AUTH_TOKEN_REQUEST = "CHECK_AUTH_TOKEN_REQUEST";
export const CHECK_AUTH_TOKEN_SUCCESS = "CHECK_AUTH_TOKEN_SUCCESS";
export const CHECK_AUTH_TOKEN_FAIL = "CHECK_AUTH_TOKEN_FAIL";

/*****USERS********/
export const USER_CASH_REGISTER_UPDATE = "USER_CASH_REGISTER_UPDATE";

export const USER_START = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const ON_EDIT_USER = "ON_EDIT_USER";

export const USER_GET_DETAILS_REQUEST = "USER_GET_DETAILS_REQUEST";
export const USER_GET_DETAILS_SUCCESS = "USER_GET_DETAILS_SUCCESS";
export const USER_GET_DETAILS_FAIL = "USER_GET_DETAILS_FAIL";

export const ADD_USER_FILTER = "ADD_USER_FILTER";
export const DELETE_USER_FILTER = "DELETE_USER_FILTER";
export const SET_USER_CURRENT_VIEW = "SET_USER_CURRENT_VIEW";

export const REQUEST_ADDITIONAL_USER_TIERS = "REQUEST_ADDITIONAL_USER_TIERS";
export const FETCH_ADDITIONAL_USER_TIERS_SUCCESS =
  "FETCH_ADDITIONAL_USER_TIERS_SUCCESS";
export const FETCH_ADDITIONAL_USER_TIERS_FAIL =
  "FETCH_ADDITIONAL_USER_TIERS_FAIL";

export const REQUEST_ADDITIONAL_USER_TIER_CREATE =
  "REQUEST_ADDITIONAL_USER_TIER_CREATE";
export const ADDITIONAL_USER_TIER_CREATE_SUCCESS =
  "ADDITIONAL_USER_TIER_CREATE_SUCCESS";
export const ADDITIONAL_USER_TIER_CREATE_FAIL =
  "ADDITIONAL_USER_TIER_CREATE_FAIL";

export const REQUEST_ADDITIONAL_USER_TIER_DELETE =
  "REQUEST_ADDITIONAL_USER_TIER_DELETE";
export const ADDITIONAL_USER_TIER_DELETE_SUCCESS =
  "ADDITIONAL_USER_TIER_DELETE_SUCCESS";
export const ADDITIONAL_USER_TIER_DELETE_FAIL =
  "ADDITIONAL_USER_TIER_DELETE_FAIL";

/*****ROLES********/
export const CMODULE_REQUEST = "CMODULE_REQUEST";
export const CMODULE_SUCCESS = "CMODULE_SUCCESS";
export const CMODULE_FAIL = "CMODULE_FAIL";

export const ROLE_REQUEST = "ROLE_REQUEST";
export const ROLE_SUCCESS = "ROLE_SUCCESS";
export const ROLE_FAIL = "ROLE_FAIL";

export const ROLE_TREEDATA_REQUEST = "ROLE_TREEDATA_REQUEST";
export const ROLE_TREEDATA_SUCCESS = "ROLE_TREEDATA_SUCCESS";
export const ROLE_TREEDATA_FAIL = "ROLE_TREEDATA_FAIL";

export const ROLE_CREATE_REQUEST = "ROLE_CREATE_REQUEST";
export const ROLE_CREATE_SUCCESS = "ROLE_CREATE_SUCCESS";
export const ROLE_CREATE_FAIL = "ROLE_CREATE_FAIL";

export const ON_EDIT_ROLE = "ON_EDIT_ROLE";

export const ROLE_UPDATE_REQUEST = "ROLE_UPDATE_REQUEST";
export const ROLE_UPDATE_SUCCESS = "ROLE_UPDATE_SUCCESS";
export const ROLE_UPDATE_FAIL = "ROLE_UPDATE_FAIL";

export const ROLE_DELETE_REQUEST = "ROLE_DELETE_REQUEST";
export const ROLE_DELETE_SUCCESS = "ROLE_DELETE_SUCCESS";
export const ROLE_DELETE_FAIL = "ROLE_DELETE_FAIL";

export const ROLE_GET_REQUEST = "ROLE_GET_REQUEST";
export const ROLE_GET_SUCCESS = "ROLE_GET_SUCCESS";
export const ROLE_GET_FAIL = "ROLE_GET_FAIL";

export const ADD_ROLE_FILTER = "ADD_ROLE_FILTER";
export const DELETE_ROLE_FILTER = "DELETE_ROLE_FILTER";
export const RESET_ROLE_DATA = "RESET_ROLE_DATA";

/*****ROLES PRIVILEGE TEMPLATE ********/
export const ROLE_TEMPLATE_REQUEST = "ROLE_TEMPLATE_REQUEST";
export const ROLE_TEMPLATE_SUCCESS = "ROLE_TEMPLATE_SUCCESS";
export const ROLE_TEMPLATE_FAIL = "ROLE_TEMPLATE_FAIL";

export const ROLE_TEMPLATE_CREATE_REQUEST = "ROLE_TEMPLATE_CREATE_REQUEST";
export const ROLE_TEMPLATE_CREATE_SUCCESS = "ROLE_TEMPLATE_CREATE_SUCCESS";
export const ROLE_TEMPLATE_CREATE_FAIL = "ROLE_TEMPLATE_CREATE_FAIL";

export const ROLE_TEMPLATE_UPDATE_REQUEST = "ROLE_TEMPLATE_UPDATE_REQUEST";
export const ROLE_TEMPLATE_UPDATE_SUCCESS = "ROLE_TEMPLATE_UPDATE_SUCCESS";
export const ROLE_TEMPLATE_UPDATE_FAIL = "ROLE_TEMPLATE_UPDATE_FAIL";

export const ROLE_TEMPLATE_DELETE_REQUEST = "ROLE_TEMPLATE_DELETE_REQUEST";
export const ROLE_TEMPLATE_DELETE_SUCCESS = "ROLE_TEMPLATE_DELETE_SUCCESS";
export const ROLE_TEMPLATE_DELETE_FAIL = "ROLE_TEMPLATE_DELETE_FAIL";

export const ON_EDIT_ROLE_TEMPLATE = "ON_EDIT_ROLE_TEMPLATE";

export const ROLE_TEMPLATE_GET_DETAILS_REQUEST =
  "ROLE_TEMPLATE_GET_DETAILS_REQUEST";
export const ROLE_TEMPLATE_GET_DETAILS_SUCCESS =
  "ROLE_TEMPLATE_GET_DETAILS_SUCCESS";
export const ROLE_TEMPLATE_GET_DETAILS_FAIL = "ROLE_TEMPLATE_GET_DETAILS_FAIL";

export const ADD_ROLE_TEMPLATE_FILTER = "ADD_ROLE_TEMPLATE_FILTER";
export const DELETE_ROLE_TEMPLATE_FILTER = "DELETE_ROLE_TEMPLATE_FILTER";
export const RESET_ROLE_TEMPLATE_DATA = "RESET_ROLE_TEMPLATE_DATA";
/*****LOCATIONS********/
export const LOCATION_REQUEST = "LOCATION_REQUEST";
export const LOCATION_SUCCESS = "LOCATION_SUCCESS";
export const LOCATION_FAIL = "LOCATION_FAIL";

export const LOCATION_GET_DETAILS_REQUEST = "LOCATION_GET_DETAILS_REQUEST";
export const LOCATION_GET_DETAILS_SUCCESS = "LOCATION_GET_DETAILS_SUCCESS";
export const LOCATION_GET_DETAILS_FAIL = "LOCATION_GET_DETAILS_FAIL";

export const LOCATION_UPDATE_REQUEST = "LOCATION_UPDATE_REQUEST";
export const LOCATION_UPDATE_SUCCESS = "LOCATION_UPDATE_SUCCESS";
export const LOCATION_UPDATE_FAIL = "LOCATION_UPDATE_FAIL";

/*****CRM ENTITY MODULES********/
export const MODULE_REQUEST = "MODULE_REQUEST";
export const MODULE_SUCCESS = "MODULE_SUCCESS";
export const MODULE_FAIL = "MODULE_FAIL";

export const MODULE_BY_NAME_REQUEST = "MODULE_BY_NAME_REQUEST";
export const MODULE_BY_NAME_SUCCESS = "MODULE_BY_NAME_SUCCESS";
export const MODULE_BY_NAME_FAIL = "MODULE_BY_NAME_FAIL";

/***** CUSTOMER ********/
export const CUSTOMER_RESET = "CUSTOMER_RESET";
export const CUSTOMER_START = "CUSTOMER_START";
export const CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS";
export const CUSTOMER_FAIL = "CUSTOMER_FAIL";

export const CUSTOMER_CREATE_REQUEST = "CUSTOMER_CREATE_REQUEST";
export const CUSTOMER_CREATE_SUCCESS = "CUSTOMER_CREATE_SUCCESS";
export const CUSTOMER_CREATE_FAIL = "CUSTOMER_CREATE_FAIL";

export const CUSTOMER_UPDATE_REQUEST = "CUSTOMER_UPDATE_REQUEST";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_FAIL = "CUSTOMER_UPDATE_FAIL";

export const CUSTOMER_DELETE_REQUEST = "CUSTOMER_DELETE_REQUEST";
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS";
export const CUSTOMER_DELETE_FAIL = "CUSTOMER_DELETE_FAIL";

export const ON_ADD_CUSTOMER_FILTER = "ON_ADD_CUSTOMER_FILTER";
export const ON_DELETE_CUSTOMER_FILTER = "ON_DELETE_CUSTOMER_FILTER";
export const ON_ADD_CUSTOMER_SORT = "ON_ADD_CUSTOMER_SORT";
export const ON_SET_CUSTOMER_CURRENT_VIEW = "ON_SET_CUSTOMER_CURRENT_VIEW";

export const CUSTOMER_GET_DETAILS_REQUEST = "CUSTOMER_GET_DETAILS_REQUEST";
export const CUSTOMER_GET_DETAILS_SUCCESS = "CUSTOMER_GET_DETAILS_SUCCESS";
export const CUSTOMER_GET_DETAILS_FAIL = "CUSTOMER_GET_DETAILS_FAIL";

export const DEFAULT_CUSTOMER_GET_DETAILS_REQUEST =
  "DEFAULT_CUSTOMER_GET_DETAILS_REQUEST";
export const DEFAULT_CUSTOMER_GET_DETAILS_SUCCESS =
  "DEFAULT_CUSTOMER_GET_DETAILS_SUCCESS";
export const DEFAULT_CUSTOMER_GET_DETAILS_FAIL =
  "DEFAULT_CUSTOMER_GET_DETAILS_FAIL";

export const CUSTOMER_SEARCH_REQUEST = "CUSTOMER_SEARCH_REQUEST";
export const CUSTOMER_SEARCH_SUCCESS = "CUSTOMER_SEARCH_SUCCESS";
export const CUSTOMER_SEARCH_FAIL = "CUSTOMER_SEARCH_FAIL";

export const CUSTOMER_LOYALTY_POINTS_HISTORY_FETCH =
  "CUSTOMER_LOYALTY_POINTS_HISTORY_FETCH";
export const CUSTOMER_LOYALTY_POINTS_HISTORY_SUCCESS =
  "CUSTOMER_LOYALTY_POINTS_HISTORY_SUCCESS";
export const CUSTOMER_LOYALTY_POINTS_HISTORY_FAIL =
  "CUSTOMER_LOYALTY_POINTS_HISTORY_FAIL";
/***** CUSTOMER ADDRESS ********/
export const CUSTOMER_ADDRESS_RESET = "CUSTOMER_ADDRESS_RESET";
export const CUSTOMER_ADDRESS_START = "CUSTOMER_ADDRESS_REQUEST";
export const CUSTOMER_ADDRESS_SUCCESS = "CUSTOMER_ADDRESS_SUCCESS";
export const CUSTOMER_ADDRESS_FAIL = "CUSTOMER_ADDRESS_FAIL";

export const CUSTOMER_ADDRESS_CREATE_REQUEST =
  "CUSTOMER_ADDRESS_CREATE_REQUEST";
export const CUSTOMER_ADDRESS_CREATE_SUCCESS =
  "CUSTOMER_ADDRESS_CREATE_SUCCESS";
export const CUSTOMER_ADDRESS_CREATE_FAIL = "CUSTOMER_ADDRESS_CREATE_FAIL";

export const CUSTOMER_ADDRESS_UPDATE_REQUEST =
  "CUSTOMER_ADDRESS_UPDATE_REQUEST";
export const CUSTOMER_ADDRESS_UPDATE_SUCCESS =
  "CUSTOMER_ADDRESS_UPDATE_SUCCESS";
export const CUSTOMER_ADDRESS_UPDATE_FAIL = "CUSTOMER_ADDRESS_UPDATE_FAIL";

export const CUSTOMER_ADDRESS_DELETE_REQUEST =
  "CUSTOMER_ADDRESS_DELETE_REQUEST";
export const CUSTOMER_ADDRESS_DELETE_SUCCESS =
  "CUSTOMER_ADDRESS_DELETE_SUCCESS";
export const CUSTOMER_ADDRESS_DELETE_FAIL = "CUSTOMER_ADDRESS_DELETE_FAIL";

export const ON_EDIT_CUSTOMER_ADDRESS = "ON_EDIT_CUSTOMER_ADDRESS";

export const CUSTOMER_ADDRESS_GET_DETAILS_REQUEST =
  "CUSTOMER_ADDRESS_GET_DETAILS_REQUEST";
export const CUSTOMER_ADDRESS_GET_DETAILS_SUCCESS =
  "CUSTOMER_ADDRESS_GET_DETAILS_SUCCESS";
export const CUSTOMER_ADDRESS_GET_DETAILS_FAIL =
  "CUSTOMER_ADDRESS_GET_DETAILS_FAIL";

export const ON_ADD_CUSTOMER_ADDRESS_FILTER = "ON_ADD_CUSTOMER_ADDRESS_FILTER";
export const ON_DELETE_CUSTOMER_ADDRESS_FILTER =
  "ON_DELETE_CUSTOMER_ADDRESS_FILTER";

export const ON_CLEAR_CUSTOMER_DETAILS = "ON_CLEAR_CUSTOMER_DETAILS";

/*** Customer Service History */
export const CUSTOMER_SERVICE_LIST_REQUEST = "CUSTOMER_SERVICE_LIST_REQUEST";
export const CUSTOMER_SERVICE_LIST_SUCCESS = "CUSTOMER_SERVICE_LIST_SUCCESS";
export const CUSTOMER_SERVICE_LIST_FAIL = "CUSTOMER_SERVICE_LIST_FAIL";
export const ON_ADD_CUSTOMER_SERVICE_FILTER = "ON_ADD_CUSTOMER_SERVICE_FILTER";
export const ON_DELETE_CUSTOMER_SERVICE_FILTER =
  "ON_DELETE_CUSTOMER_SERVICE_FILTER";

/***** CUSTOM VIEW ********/
export const CUSTOM_VIEW_REQUEST = "CUSTOM_VIEW_REQUEST";
export const CUSTOM_VIEW_SUCCESS = "CUSTOM_VIEW_SUCCESS";
export const CUSTOM_VIEW_FAIL = "CUSTOM_VIEW_FAIL";

export const CUSTOM_VIEW_CREATE_REQUEST = "CUSTOM_VIEW_CREATE_REQUEST";
export const CUSTOM_VIEW_CREATE_SUCCESS = "CUSTOM_VIEW_CREATE_SUCCESS";
export const CUSTOM_VIEW_CREATE_FAIL = "CUSTOM_VIEW_CREATE_FAIL";

export const ON_EDIT_CUSTOM_VIEW = "ON_EDIT_CUSTOM_VIEW";

export const CUSTOM_VIEW_UPDATE_REQUEST = "CUSTOM_VIEW_UPDATE_REQUEST";
export const CUSTOM_VIEW_UPDATE_SUCCESS = "CUSTOM_VIEW_UPDATE_SUCCESS";
export const CUSTOM_VIEW_UPDATE_FAIL = "CUSTOM_VIEW_UPDATE_FAIL";

export const CUSTOM_VIEW_DELETE_REQUEST = "CUSTOM_VIEW_DELETE_REQUEST";
export const CUSTOM_VIEW_DELETE_SUCCESS = "CUSTOM_VIEW_DELETE_SUCCESS";
export const CUSTOM_VIEW_DELETE_FAIL = "CUSTOM_VIEW_DELETE_FAIL";

/***** COMPANY DETAILS ********/
export const COMPANY_GET_DETAILS_REQUEST = "COMPANY_GET_DETAILS_REQUEST";
export const COMPANY_GET_DETAILS_SUCCESS = "COMPANY_GET_DETAILS_SUCCESS";
export const COMPANY_GET_DETAILS_FAIL = "COMPANY_GET_DETAILS_FAIL";

export const COMPANY_UPDATE_REQUEST = "COMPANY_UPDATE_REQUEST";
export const COMPANY_UPDATE_SUCCESS = "COMPANY_UPDATE_SUCCESS";
export const COMPANY_UPDATE_FAIL = "COMPANY_UPDATE_FAIL";

/***** VENDOR ********/
export const VENDOR_RESET = "VENDOR_RESET";
export const VENDOR_START = "VENDOR_REQUEST";
export const VENDOR_SUCCESS = "VENDOR_SUCCESS";
export const VENDOR_FAIL = "VENDOR_FAIL";

export const VENDOR_CREATE_REQUEST = "VENDOR_CREATE_REQUEST";
export const VENDOR_CREATE_SUCCESS = "VENDOR_CREATE_SUCCESS";
export const VENDOR_CREATE_FAIL = "VENDOR_CREATE_FAIL";

export const VENDOR_UPDATE_REQUEST = "VENDOR_UPDATE_REQUEST";
export const VENDOR_UPDATE_SUCCESS = "VENDOR_UPDATE_SUCCESS";
export const VENDOR_UPDATE_FAIL = "VENDOR_UPDATE_FAIL";

export const VENDOR_DELETE_REQUEST = "VENDOR_DELETE_REQUEST";
export const VENDOR_DELETE_SUCCESS = "VENDOR_DELETE_SUCCESS";
export const VENDOR_DELETE_FAIL = "VENDOR_DELETE_FAIL";

export const ON_EDIT_VENDOR = "ON_EDIT_VENDOR";

export const VENDOR_GET_DETAILS_REQUEST = "VENDOR_GET_DETAILS_REQUEST";
export const VENDOR_GET_DETAILS_SUCCESS = "VENDOR_GET_DETAILS_SUCCESS";
export const VENDOR_GET_DETAILS_FAIL = "VENDOR_GET_DETAILS_FAIL";

export const ON_ADD_VENDOR_FILTER = "ON_ADD_VENDOR_FILTER";
export const ON_DELETE_VENDOR_FILTER = "ON_DELETE_VENDOR_FILTER";

export const ADD_VENDOR_FILTER = "ADD_VENDOR_FILTER";
export const DELETE_VENDOR_FILTER = "DELETE_VENDOR_FILTER";
export const SET_VENDOR_CURRENT_VIEW = "SET_VENDOR_CURRENT_VIEW";
export const ADD_VENDOR_SORT = "ADD_VENDOR_SORT";

/***** VENDOR ADDRESS ********/
export const VENDOR_ADDRESS_RESET = "VENDOR_ADDRESS_RESET";
export const VENDOR_ADDRESS_START = "VENDOR_ADDRESS_REQUEST";
export const VENDOR_ADDRESS_SUCCESS = "VENDOR_ADDRESS_SUCCESS";
export const VENDOR_ADDRESS_FAIL = "VENDOR_ADDRESS_FAIL";

export const VENDOR_ADDRESS_CREATE_REQUEST = "VENDOR_ADDRESS_CREATE_REQUEST";
export const VENDOR_ADDRESS_CREATE_SUCCESS = "VENDOR_ADDRESS_CREATE_SUCCESS";
export const VENDOR_ADDRESS_CREATE_FAIL = "VENDOR_ADDRESS_CREATE_FAIL";

export const VENDOR_ADDRESS_UPDATE_REQUEST = "VENDOR_ADDRESS_UPDATE_REQUEST";
export const VENDOR_ADDRESS_UPDATE_SUCCESS = "VENDOR_ADDRESS_UPDATE_SUCCESS";
export const VENDOR_ADDRESS_UPDATE_FAIL = "VENDOR_ADDRESS_UPDATE_FAIL";

export const VENDOR_ADDRESS_DELETE_REQUEST = "VENDOR_ADDRESS_DELETE_REQUEST";
export const VENDOR_ADDRESS_DELETE_SUCCESS = "VENDOR_ADDRESS_DELETE_SUCCESS";
export const VENDOR_ADDRESS_DELETE_FAIL = "VENDOR_ADDRESS_DELETE_FAIL";

export const ON_EDIT_VENDOR_ADDRESS = "ON_EDIT_VENDOR_ADDRESS";

export const VENDOR_ADDRESS_GET_DETAILS_REQUEST =
  "VENDOR_ADDRESS_GET_DETAILS_REQUEST";
export const VENDOR_ADDRESS_GET_DETAILS_SUCCESS =
  "VENDOR_ADDRESS_GET_DETAILS_SUCCESS";
export const VENDOR_ADDRESS_GET_DETAILS_FAIL =
  "VENDOR_ADDRESS_GET_DETAILS_FAIL";

export const ON_ADD_VENDOR_ADDRESS_FILTER = "ON_ADD_VENDOR_FILTER";
export const ON_DELETE_VENDOR_ADDRESS_FILTER =
  "ON_DELETE_VENDOR_ADDRESS_FILTER";

/***** PRODUCT ********/
export const PRODUCT_RESET = "PRODUCT_RESET";
export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const FEATURED_PRODUCT_REQUEST = "FEATURED_PRODUCT_REQUEST";
export const PRODUCT_FETCH_REQUEST = "PRODUCT_FETCH_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const FEATURED_PRODUCT_SUCCESS = "FEATURED_PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

export const PRODUCT_COUNT_REQUEST = "PRODUCT_COUNT_REQUEST";
export const PRODUCT_COUNT_SUCCESS = "PRODUCT_COUNT__SUCCESS";
export const PRODUCT_COUNT_FAIL = "PRODUCT_COUNT__FAIL";

export const PRODUCT_SALES_REPORT_REQUEST = "PRODUCT_SALES_REPORT_REQUEST";
export const PRODUCT_SALES_REPORT_SUCCESS = "PRODUCT_SALES_REPORT_SUCCESS";
export const PRODUCT_SALES_REPORT_FAIL = "PRODUCT_SALES_REPORT_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

export const ON_EDIT_PRODUCT = "ON_EDIT_PRODUCT";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAIL = "PRODUCT_FETCH_FAIL";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const ON_ADD_PRODUCT_FILTER = "ON_ADD_PRODUCT_FILTER";
export const ON_DELETE_PRODUCT_FILTER = "ON_DELETE_PRODUCT_FILTER";

export const ON_SET_PRODUCT_CURRENT_VIEW = "ON_SET_PRODUCT_CURRENT_VIEW";

export const PRODUCT_GET_DETAIL_REQUEST = "PRODUCT_GET_DETAIL_REQUEST";
export const PRODUCT_GET_DETAIL_SUCCESS = "PRODUCT_GET_DETAIL_SUCCESS";
export const PRODUCT_GET_DETAIL_FAIL = "PRODUCT_GET_DETAIL_FAIL";

export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_FAIL = "PRODUCT_SEARCH_FAIL";

export const PRODUCT_GET_DETAILS_FAIL = "PRODUCT_GET_DETAILS_FAIL";
export const PRODUCT_GET_DETAILS_REQUEST = "PRODUCT_GET_DETAILS_REQUEST";
export const PRODUCT_GET_DETAILS_SUCCESS = "PRODUCT_GET_DETAILS_SUCCESS";

export const ADD_PRODUCT_FILTER = "ADD_PRODUCT_FILTER";
export const ADD_PRODUCT_SORTING = "ADD_PRODUCT_SORTING";

export const PRODUCT_FETCH_RESET_REQUEST = "PRODUCT_FETCH_RESET_REQUEST";
export const DELETE_PRODUCT_FILTER = "DELETE_PRODUCT_FILTER";
export const SET_PRODUCT_CURRENT_VIEW = "SET_PRODUCT_CURRENT_VIEW";

export const PRODUCT_SET_SEARCH_TEXT = "PRODUCT_SET_SEARCH_TEXT";
export const PRODUCT_CLEAR_SEARCH_TEXT = "PRODUCT_CLEAR_SEARCH_TEXT";

/******DEPARTMENT*****/
export const DEPARTMENT_REQUEST = "DEPARTMENT_REQUEST";
export const DEPARTMENT_SUCCESS = "DEPARTMENT_SUCCESS";
export const DEPARTMENT_FAIL = "DEPARTMENT_FAIL";
export const GET_ALL_DEPARTMENT_REQUEST = "GET_ALL_DEPARTMENT_REQUEST";
export const GET_ALL_DEPARTMENT_SUCCESS = "GET_ALL_DEPARTMENT_SUCCESS";
export const GET_ALL_DEPARTMENT_FAIL = "GET_ALL_DEPARTMENT_FAIL";
export const DEPPARTMENT_RESET_LIST = "DEPPARTMENT_RESET_LIST";

/******SALESGROUP*****/
export const SALESGROUP_REQUEST = "SALESGROUP_REQUEST";
export const SALESGROUP_SUCCESS = "SALESGROUP_SUCCESS";
export const SALESGROUP_FAIL = "SALESGROUP_FAIL";
export const SALESGROUP_RESET_LIST = "SALESGROUP_RESET_LIST";

/*****CATEGORY********/
export const CATEGORY_RESET = "CATEGORY_RESET";
export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_BY_GROUP_REQUEST = "CATEGORY_BY_GROUP_REQUEST";

export const CATEGORY_ALL_REQUEST = "CATEGORY_ALL_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";
export const CATEGORY_RESET_LIST = "CATEGORY_RESET_LIST";

export const CATEGORY_TREEDATA_REQUEST = "CATEGORY_TREEDATA_REQUEST";
export const CATEGORY_TREEDATA_SUCCESS = "CATEGORY_TREEDATA_SUCCESS";
export const CATEGORY_TREEDATA_FAIL = "CATEGORY_TREEDATA_FAIL";

export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAIL = "CATEGORY_CREATE_FAIL";

export const ON_EDIT_CATEGORY = "ON_EDIT_CATEGORY";

export const CATEGORY_UPDATE_REQUEST = "CATEGORY_UPDATE_REQUEST";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";

export const CATEGORY_GET_DETAIL_REQUEST = "CATEGORY_GET_DETAIL_REQUEST";
export const CATEGORY_GET_DETAIL_SUCCESS = "CATEGORY_GET_DETAIL_SUCCESS";
export const CATEGORY_GET_DETAIL_FAIL = "CATEGORY_GET_DETAIL_FAIL";

export const ADD_CATEGORY_FILTER = "ADD_CATEGORY_FILTER";
export const DELETE_CATEGORY_FILTER = "DELETE_CATEGORY_FILTER";
export const SET_CATEGORY_CURRENT_VIEW = "SET_CATEGORY_CURRENT_VIEW";

export const CATEGORY_SET_DETAILS = "CATEGORY_SET_DETAILS";

/*****ATTRIBUTE********/
export const ATTRIBUTE_RESET = "ATTRIBUTE_RESET";
export const ATTRIBUTE_REQUEST = "ATTRIBUTE_REQUEST";
export const ATTRIBUTE_SUCCESS = "ATTRIBUTE_SUCCESS";
export const ATTRIBUTE_FAIL = "ATTRIBUTE_FAIL";

export const ATTRIBUTE_TREEDATA_REQUEST = "ATTRIBUTE_TREEDATA_REQUEST";
export const ATTRIBUTE_TREEDATA_SUCCESS = "ATTRIBUTE_TREEDATA_SUCCESS";
export const ATTRIBUTE_TREEDATA_FAIL = "ATTRIBUTE_TREEDATA_FAIL";

export const ATTRIBUTE_CREATE_REQUEST = "ATTRIBUTE_CREATE_REQUEST";
export const ATTRIBUTE_CREATE_SUCCESS = "ATTRIBUTE_CREATE_SUCCESS";
export const ATTRIBUTE_CREATE_FAIL = "ATTRIBUTE_CREATE_FAIL";

export const ON_EDIT_ATTRIBUTE = "ON_EDIT_ATTRIBUTE";

export const ATTRIBUTE_UPDATE_REQUEST = "ATTRIBUTE_UPDATE_REQUEST";
export const ATTRIBUTE_UPDATE_SUCCESS = "ATTRIBUTE_UPDATE_SUCCESS";
export const ATTRIBUTE_UPDATE_FAIL = "ATTRIBUTE_UPDATE_FAIL";

export const ATTRIBUTE_DELETE_REQUEST = "ATTRIBUTE_DELETE_REQUEST";
export const ATTRIBUTE_DELETE_SUCCESS = "ATTRIBUTE_DELETE_SUCCESS";
export const ATTRIBUTE_DELETE_FAIL = "ATTRIBUTE_DELETE_FAIL";

export const ATTRIBUTE_GET_DETAIL_REQUEST = "ATTRIBUTE_GET_DETAIL_REQUEST";
export const ATTRIBUTE_GET_DETAIL_SUCCESS = "ATTRIBUTE_GET_DETAIL_SUCCESS";
export const ATTRIBUTE_GET_DETAIL_FAIL = "ATTRIBUTE_GET_DETAIL_FAIL";

export const ATTRIBUTE_SET_DETAILS = "ATTRIBUTE_SET_DETAILS";

export const ADD_ATTRIBUTE_FILTER = "ADD_ATTRIBUTE_FILTER";
export const DELETE_ATTRIBUTE_FILTER = "DELETE_ATTRIBUTE_FILTER";

/*****UOM********/
export const UOM_REQUEST = "UOM_REQUEST";
export const UOM_SUCCESS = "UOM_SUCCESS";
export const UOM_FAIL = "UOM_FAIL";

export const UOM_TREEDATA_REQUEST = "UOM_TREEDATA_REQUEST";
export const UOM_TREEDATA_SUCCESS = "UOM_TREEDATA_SUCCESS";
export const UOM_TREEDATA_FAIL = "UOM_TREEDATA_FAIL";

export const UOM_CREATE_REQUEST = "UOM_CREATE_REQUEST";
export const UOM_CREATE_SUCCESS = "UOM_CREATE_SUCCESS";
export const UOM_CREATE_FAIL = "UOM_CREATE_FAIL";

export const ON_EDIT_UOM = "ON_EDIT_UOM";

export const UOM_UPDATE_REQUEST = "UOM_UPDATE_REQUEST";
export const UOM_UPDATE_SUCCESS = "UOM_UPDATE_SUCCESS";
export const UOM_UPDATE_FAIL = "UOM_UPDATE_FAIL";

export const UOM_DELETE_REQUEST = "UOM_DELETE_REQUEST";
export const UOM_DELETE_SUCCESS = "UOM_DELETE_SUCCESS";
export const UOM_DELETE_FAIL = "UOM_DELETE_FAIL";

export const UOM_GET_DETAIL_REQUEST = "UOM_GET_DETAIL_REQUEST";
export const UOM_GET_DETAIL_SUCCESS = "UOM_GET_DETAIL_SUCCESS";
export const UOM_GET_DETAIL_FAIL = "UOM_GET_DETAIL_FAIL";

export const UOM_SET_DETAILS = "UOM_SET_DETAILS";

/*****SALESORDER********/
export const SALESORDER_REQUEST = "SALESORDER_REQUEST";
export const SALESORDER_SUCCESS = "SALESORDER_SUCCESS";
export const SALESORDER_FAIL = "SALESORDER_FAIL";

export const SALESORDER_CREATE_REQUEST = "SALESORDER_CREATE_REQUEST";
export const SALESORDER_CREATE_SUCCESS = "SALESORDER_CREATE_SUCCESS";
export const SALESORDER_CREATE_FAIL = "SALESORDER_CREATE_FAIL";

export const SALESORDER_RETURN_CREATE_REQUEST =
  "SALESORDER_RETURN_CREATE_REQUEST";
export const SALESORDER_RETURN_CREATE_SUCCESS =
  "SALESORDER_RETURN_CREATE_SUCCESS";
export const SALESORDER_RETURN_CREATE_FAIL = "SALESORDER_RETURN_CREATE_FAIL";

export const SALESORDER_RETURN_UPDATE_REQUEST =
  "SALESORDER_RETURN_UPDATE_REQUEST";
export const SALESORDER_RETURN_UPDATE_SUCCESS =
  "SALESORDER_RETURN_UPDATE_SUCCESS";
export const SALESORDER_RETURN_UPDATE_FAIL = "SALESORDER_RETURN_UPDATE_FAIL";

export const SALESORDER_UPDATE_REQUEST = "SALESORDER_UPDATE_REQUEST";
export const SALESORDER_UPDATE_SUCCESS = "SALESORDER_UPDATE_SUCCESS";
export const SALESORDER_UPDATE_FAIL = "SALESORDER_UPDATE_FAIL";

export const SALESORDER_DELETE_REQUEST = "SALESORDER_DELETE_REQUEST";
export const SALESORDER_DELETE_SUCCESS = "SALESORDER_DELETE_SUCCESS";
export const SALESORDER_DELETE_FAIL = "SALESORDER_DELETE_FAIL";
export const SALESORDER_RESET_REQUEST = "SALESORDER_RESET_REQUEST";

export const SALESORDER_GET_DETAIL_REQUEST = "SALESORDER_GET_DETAIL_REQUEST";
export const SALESORDER_GET_DETAIL_SUCCESS = "SALESORDER_GET_DETAIL_SUCCESS";
export const SALESORDER_GET_DETAIL_FAIL = "SALESORDER_GET_DETAIL_FAIL";

export const ON_ADD_SALESORDER_FILTER = "ON_ADD_SALESORDER_FILTER";
export const ON_DELETE_SALESORDER_FILTER = "ON_DELETE_SALESORDER_FILTER";
export const ON_SET_SALESORDER_CURRENT_VIEW = "ON_SET_SALESORDER_CURRENT_VIEW";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";

export const SALESORDER_GET_REFERENCE_DETAILS_REQUEST =
  "SALESORDER_GET_REFERENCE_DETAILS_REQUEST"; //V2W-386
export const SALESORDER_GET_REFERENCE_DETAILS_REQUEST_SUCCESS =
  "SALESORDER_GET_REFERENCE_DETAILS_REQUEST_SUCCESS";
export const SALESORDER_GET_REFERENCE_DETAILS_REQUEST_FAIL =
  "SALESORDER_GET_REFERENCE_DETAILS_REQUEST_FAIL";

export const SALESORDER_CANCEL_PAYMENT_REQUEST =
  "SALESORDER_CANCEL_PAYMENT_REQUEST";
export const SALESORDER_CANCEL_PAYMENT_SUCCESS =
  "SALESORDER_CANCEL_PAYMENT_SUCCESS";

export const SALESORDER_CANCEL_PAYMENT_FAIL = "SALESORDER_CANCEL_PAYMENT_FAIL";

export const RELATED_SO_GET_REQUEST = "RELATED_SO_GET_REQUEST";
export const RELATED_SO_GET_SUCCESS = "RELATED_SO_GET_SUCCESS";
export const RELATED_SO_GET_FAIL = "RELATED_SO_GET_FAIL";

//SALES ORDER ORDER AND DELIVERY TRACKING STATUS
export const ORDER_TRACKING_STATUS_LIST_REQUEST =
  "ORDER_TRACKING_STATUS_LIST_REQUEST";
export const ORDER_TRACKING_STATUS_LIST_SUCCESS =
  "ORDER_TRACKING_STATUS_LIST_SUCCESS";
export const ORDER_TRACKING_STATUS_LIST_FAIL =
  "ORDER_TRACKING_STATUS_LIST_FAIL";

//BATCH CLOSE REQUEST
export const BATCH_CLOSE_GET_DATA_REQUEST = "BATCH_CLOSE_GET_DATA_REQUEST";
export const BATCH_CLOSE_GET_DATA_SUCCESS = "BATCH_CLOSE_GET_DATA_SUCCESS";
export const BATCH_CLOSE_GET_DATA_FAIL = "BATCH_CLOSE_GET_DATA_FAIL";

//BATCH CLOSE REQUEST
export const BATCH_CLOSE_REQUEST = "BATCH_CLOSE_REQUEST";
export const BATCH_CLOSE_SUCCESS = "BATCH_CLOSE_SUCCESS";
export const BATCH_CLOSE_FAIL = "BATCH_CLOSE_FAIL";

/*****PURCHASEORDER********/
export const PURCHASEORDER_RECEIPT_REQUEST = "PURCHASEORDER_RECEIPT_REQUEST";
export const PURCHASEORDER_RECEIPT_REQUEST_SUCCESS =
  "PURCHASEORDER_RECEIPT_REQUEST_SUCCESS";
export const PURCHASEORDER_RECEIPT_REQUEST_FAIL =
  "PURCHASEORDER_RECEIPT_REQUEST_FAIL";

export const PURCHASEORDER_RECEIPT_DETAILS_BY_ID_REQUEST =
  "PURCHASEORDER_RECEIPT_REQUEST_BY_ID_REQUEST";
export const PURCHASEORDER_RECEIPT_DETAILS_BY_ID_SUCCESS =
  "PURCHASEORDER_RECEIPT_DETAILS_BY_ID_SUCCESS";
export const PURCHASEORDER_RECEIPT_DETAILS_BY_ID_FAIL =
  "PURCHASEORDER_RECEIPT_DETAILS_BY_ID_FAIL";

export const PURCHASEORDER_RESET = "PURCHASEORDER_RESET";
export const PURCHASEORDER_REQUEST = "PURCHASEORDER_REQUEST";
export const PURCHASEORDER_SUCCESS = "PURCHASEORDER_SUCCESS";
export const PURCHASEORDER_FAIL = "PURCHASEORDER_FAIL";

export const PURCHASEORDER_CREATE_REQUEST = "PURCHASEORDER_CREATE_REQUEST";
export const PURCHASEORDER_CREATE_SUCCESS = "PURCHASEORDER_CREATE_SUCCESS";
export const PURCHASEORDER_CREATE_FAIL = "PURCHASEORDER_CREATE_FAIL";

export const PURCHASEORDER_RESET_REQUEST = "PURCHASEORDER_RESET_REQUEST";
export const PURCHASEORDER_RETURN_CREATE_REQUEST =
  "PURCHASEORDER_RETURN_CREATE_REQUEST";
export const PURCHASEORDER_RETURN_CREATE_SUCCESS =
  "PURCHASEORDER_RETURN_CREATE_SUCCESS";
export const PURCHASEORDER_RETURN_CREATE_FAIL =
  "PURCHASEORDER_RETURN_CREATE_FAIL";

export const PURCHASEORDER_UPDATE_REQUEST = "PURCHASEORDER_UPDATE_REQUEST";
export const PURCHASEORDER_UPDATE_SUCCESS = "PURCHASEORDER_UPDATE_SUCCESS";
export const PURCHASEORDER_UPDATE_FAIL = "PURCHASEORDER_UPDATE_FAIL";

export const PURCHASEORDER_DELETE_REQUEST = "PURCHASEORDER_DELETE_REQUEST";
export const PURCHASEORDER_DELETE_SUCCESS = "PURCHASEORDER_DELETE_SUCCESS";
export const PURCHASEORDER_DELETE_FAIL = "PURCHASEORDER_DELETE_FAIL";

export const PURCHASEORDER_GET_DETAIL_REQUEST =
  "PURCHASEORDER_GET_DETAIL_REQUEST";
export const PURCHASEORDER_GET_DETAIL_SUCCESS =
  "PURCHASEORDER_GET_DETAIL_SUCCESS";
export const PURCHASEORDER_GET_DETAIL_FAIL = "PURCHASEORDER_GET_DETAIL_FAIL";

export const ON_ADD_PURCHASEORDER_FILTER = "ON_ADD_PURCHASEORDER_FILTER";
export const ON_DELETE_PURCHASEORDER_FILTER = "ON_DELETE_PURCHASEORDER_FILTER";
export const ON_SET_PURCHASEORDER_CURRENT_VIEW =
  "ON_SET_PURCHASEORDER_CURRENT_VIEW";

export const PURCHASEORDER_RECEIVE_REQUEST = "PURCHASEORDER_RECEIVE_REQUEST";
export const PURCHASEORDER_RECEIVE_SUCCESS = "PURCHASEORDER_RECEIVE_SUCCESS";
export const PURCHASEORDER_RECEIVE_FAIL = "PURCHASEORDER_RECEIVE_FAIL";

export const PURCHASEORDER_GET_INVOICE_SUCCESS =
  "PURCHASEORDER_GET_INVOICE_SUCCESS";

/*************RECEIVE_PURCHASEORDER_GET_DETAIL_REQUEST********** */

export const RECEIVE_PURCHASEORDER_GET_DETAIL_REQUEST =
  "RECEIVE_PURCHASEORDER_GET_DETAIL_REQUEST";
export const RECEIVE_PURCHASEORDER_GET_DETAIL_SUCCESS =
  "RECEIVE_PURCHASEORDER_GET_DETAIL_SUCCESS";
export const RECEIVE_PURCHASEORDER_GET_DETAIL_FAIL =
  "RECEIVE_PURCHASEORDER_GET_DETAIL_FAIL";

/*****UNIT OF MESUAREMENT********/
export const UNIT_RESET = "UNIT_RESET";
export const UNITS_REQUEST = "UNITS_REQUEST";
export const UNITS_SUCCESS = "UNITS_SUCCESS";
export const UNITS_FAIL = "UNITS_FAIL";

export const UNIT_CREATE_REQUEST = "UNIT_CREATE_REQUEST";
export const UNIT_CREATE_SUCCESS = "UNIT_CREATE_SUCCESS";
export const UNIT_CREATE_FAIL = "UNIT_CREATE_FAIL";

export const UNIT_UPDATE_REQUEST = "UNIT_UPDATE_REQUEST";
export const UNIT_UPDATE_SUCCESS = "UNIT_UPDATE_SUCCESS";
export const UNIT_UPDATE_FAIL = "UNIT_UPDATE_FAIL";

export const UNIT_DELETE_REQUEST = "UNIT_DELETE_REQUEST";
export const UNIT_DELETE_SUCCESS = "UNIT_DELETE_SUCCESS";
export const UNIT_DELETE_FAIL = "UNIT_DELETE_FAIL";

export const UNIT_GET_DETAILS_REQUEST = "UNIT_GET_DETAILS_REQUEST";
export const UNIT_GET_DETAILS_SUCCESS = "UNIT_GET_DETAILS_SUCCESS";
export const UNIT_GET_DETAILS_FAIL = "UNIT_GET_DETAILS_FAIL";

export const ADD_UNIT_FILTER = "ADD_UNIT_FILTER";
export const DELETE_UNIT_FILTER = "DELETE_UNIT_FILTER";

export const AUTH_UPDATE_USER = "AUTH_UPDATE_USER";

/*****CURRENCY********/
export const CURRENCY_RESET = "CURRENCY_RESET";
export const CURRENCY_REQUEST = "CURRENCY_REQUEST";
export const CURRENCY_SUCCESS = "CURRENCY_SUCCESS";
export const CURRENCY_FAIL = "CURRENCY_FAIL";

export const CURRENCY_CREATE_REQUEST = "CURRENCY_CREATE_REQUEST";
export const CURRENCY_CREATE_SUCCESS = "CURRENCY_CREATE_SUCCESS";
export const CURRENCY_CREATE_FAIL = "CURRENCY_CREATE_FAIL";

export const CURRENCY_UPDATE_REQUEST = "CURRENCY_UPDATE_REQUEST";
export const CURRENCY_UPDATE_SUCCESS = "CURRENCY_UPDATE_SUCCESS";
export const CURRENCY_UPDATE_FAIL = "CURRENCY_UPDATE_FAIL";

export const CURRENCY_DELETE_REQUEST = "CURRENCY_DELETE_REQUEST";
export const CURRENCY_DELETE_SUCCESS = "CURRENCY_DELETE_SUCCESS";
export const CURRENCY_DELETE_FAIL = "CURRENCY_DELETE_FAIL";

export const CURRENCY_GET_DETAILS_REQUEST = "CURRENCY_GET_DETAILS_REQUEST";
export const CURRENCY_GET_DETAILS_SUCCESS = "CURRENCY_GET_DETAILS_SUCCESS";
export const CURRENCY_GET_DETAILS_FAIL = "CURRENCY_GET_DETAILS_FAIL";

export const ADD_CURRENCY_FILTER = "ADD_CURRENCY_FILTER";
export const DELETE_CURRENCY_FILTER = "DELETE_CURRENCY_FILTER";

/*****HOME********/
export const SET_MODULE_SEQUENCE_REQUEST = "SET_MODULE_SEQUENCE_REQUEST";
export const SET_MODULE_SEQUENCE_SUCCESS = "SET_MODULE_SEQUENCE_SUCCESS";
export const SET_MODULE_SEQUENCE_FAIL = "SET_MODULE_SEQUENCE_FAIL";

export const GET_MODULE_SEQUENCE_REQUEST = "GET_MODULE_SEQUENCE_REQUEST";
export const GET_MODULE_SEQUENCE_SUCCESS = "GET_MODULE_SEQUENCE_SUCCESS";
export const GET_MODULE_SEQUENCE_FAIL = "GET_MODULE_SEQUENCE_FAIL";

/*****DASHBOARD********/
export const DASHBOARD_GROSS_PROFIT_START = "DASHBOARD_GROSS_PROFIT_START";
export const DASHBOARD_GROSS_PROFIT_FAIL = "DASHBOARD_GROSS_PROFIT_FAIL";
export const DASHBOARD_GROSS_PROFIT_SUCCESS = "DASHBOARD_GROSS_PROFIT_SUCCESS";

export const DASHBOARD_NET_PROFIT_START = "DASHBOARD_NET_PROFIT_START";
export const DASHBOARD_NET_PROFIT_FAIL = "DASHBOARD_NET_PROFIT_FAIL";
export const DASHBOARD_NET_PROFIT_SUCCESS = "DASHBOARD_NET_PROFIT_SUCCESS";

export const DASHBOARD_NO_OF_ORDERS_START = "DASHBOARD_NO_OF_ORDERS_START";
export const DASHBOARD_NO_OF_ORDERS_FAIL = "DASHBOARD_NO_OF_ORDERS_FAIL";
export const DASHBOARD_NO_OF_ORDERS_SUCCESS = "DASHBOARD_NO_OF_ORDERS_SUCCESS";

export const DASHBOARD_SO_TOTAL_START = "DASHBOARD_SO_TOTAL_START";
export const DASHBOARD_SO_TOTAL_FAIL = "DASHBOARD_SO_TOTAL_FAIL";
export const DASHBOARD_SO_TOTAL_SUCCESS = "DASHBOARD_SO_TOTAL_SUCCESS";

export const DASHBOARD_BAR_CHART_GP_START = "DASHBOARD_BAR_CHART_GP_START";
export const DASHBOARD_BAR_CHART_GP_FAIL = "DASHBOARD_BAR_CHART_GP_FAIL";
export const DASHBOARD_BAR_CHART_GP_SUCCESS = "DASHBOARD_BAR_CHART_GP_SUCCESS";

export const DASHBOARD_BAR_CHART_NP_START = "DASHBOARD_BAR_CHART_NP_START";
export const DASHBOARD_BAR_CHART_NP_FAIL = "DASHBOARD_BAR_CHART_NP_FAIL";
export const DASHBOARD_BAR_CHART_NP_SUCCESS = "DASHBOARD_BAR_CHART_NP_SUCCESS";

export const DASHBOARD_BAR_CHART_TO_START = "DASHBOARD_BAR_CHART_TO_START";
export const DASHBOARD_BAR_CHART_TO_FAIL = "DASHBOARD_BAR_CHART_TO_FAIL";
export const DASHBOARD_BAR_CHART_TO_SUCCESS = "DASHBOARD_BAR_CHART_TO_SUCCESS";

export const DASHBOARD_PIE_CHART_START = "DASHBOARD_PIE_CHART_START";
export const DASHBOARD_PIE_CHART_FAIL = "DASHBOARD_PIE_CHART_FAIL";
export const DASHBOARD_PIE_CHART_SUCCESS = "DASHBOARD_PIE_CHART_SUCCESS";

export const DASHBOARD_LINE_CHART_START = "DASHBOARD_LINE_CHART_START";
export const DASHBOARD_LINE_CHART_FAIL = "DASHBOARD_LINE_CHART_FAIL";
export const DASHBOARD_LINE_CHART_SUCCESS = "DASHBOARD_LINE_CHART_SUCCESS";

export const DASHBOARD_CATEGORY_CHART_START = "DASHBOARD_CATEGORY_CHART_START";
export const DASHBOARD_CATEGORY_CHART_FAIL = "DASHBOARD_CATEGORY_CHART_FAIL";
export const DASHBOARD_CATEGORY_CHART_SUCCESS =
  "DASHBOARD_CATEGORY_CHART_SUCCESS";

export const DASHBOARD_COLLECTED_TAX_START = "DASHBOARD_COLLECTED_TAX_START";
export const DASHBOARD_COLLECTED_TAX_FAIL = "DASHBOARD_COLLECTED_TAX_FAIL";
export const DASHBOARD_COLLECTED_TAX_SUCCESS =
  "DASHBOARD_COLLECTED_TAX_SUCCESS";

export const DASHBOARD_COLLECTED_TIP_START = "DASHBOARD_COLLECTED_TIP_START";
export const DASHBOARD_COLLECTED_TIP_FAIL = "DASHBOARD_COLLECTED_TIP_FAIL";
export const DASHBOARD_COLLECTED_TIP_SUCCESS =
  "DASHBOARD_COLLECTED_TIP_SUCCESS";

export const DASHBOARD_SET_FILTER = "DASHBOARD_SET_FILTER";

/*****ATTRIBUTE LIST********/

export const ATTRIBUTE_OPTION_LIST_REQUEST = "ATTRIBUTE_OPTION_LIST_REQUEST";
export const ATTRIBUTE_OPTION_LIST_FAIL = "ATTRIBUTE_OPTION_LIST_FAIL";
export const ATTRIBUTE_OPTION_LIST_SUCCESS = "ATTRIBUTE_OPTION_LIST_SUCCESS";

/******* REPORTS *******/
export const ADD_REPORT_FILTER = "ADD_REPORT_FILTER";
export const REPORT_START = "REPORT_START";
export const REPORT_SUCCESS = "REPORT_SUCCESS";
export const REPORT_FAIL = "REPORT_FAIL";
export const REPORT_EXPORT_START = "REPORT_EXPORT_START";
export const REPORT_EXPORT_SUCCESS = "REPORT_EXPORT_SUCCESS";
export const REPORT_EXPORT_FAIL = "REPORT_EXPORT_FAIL";
export const REPORT_SALES_HISTORY_START = "REPORT_SALES_HISTORY_START";
export const REPORT_SALES_HISTORY_SUCCESS = "REPORT_SALES_HISTORY_SUCCESS";
export const REPORT_USER_SALES_START = "REPORT_USER_SALES_START";
export const USER_SALES_EXPORT_START = "USER_SALES_EXPORT_START";
export const REPORT_USER_SALES_SUCCESS = "REPORT_USER_SALES_SUCCESS";
export const REPORT_SALES_HISTORY_FAIL = "REPORT_SALES_HISTORY_FAIL";
export const RESET_REPORT_DATA = "RESET_REPORT_DATA";
export const DAILY_SALES_REPORT_START = "DAILY_SALES_REPORT_START";
export const DAILY_SALES_REPORT_SUCCESS = "DAILY_SALES_REPORT_SUCCESS";
export const DAILY_SALES_REPORT_FAIL = "DAILY_SALES_REPORT_FAIL";
export const SALES_HISTORY_EXPORT_START = "SALES_HISTORY_EXPORT_START";
export const SALES_HISTORY_EXPORT_SUCCESS = "SALES_HISTORY_EXPORT_SUCCESS";
export const SALES_HISTORY_EXPORT_FAIL = "SALES_HISTORY_EXPORT_FAIL";
export const CUSTOMER_SALES_EXPORT_START = "CUSTOMER_SALES_EXPORT_START";
export const CUSTOMER_SALES_EXPORT_SUCCESS = "CUSTOMER_SALES_EXPORT_SUCCESS";
export const CUSTOMER_SALES_EXPORT_FAIL = "CUSTOMER_SALES_EXPORT_FAIL";
export const USER_SALES_EXPORT_SUCCESS = "USER_SALES_EXPORT_SUCCESS";
export const USER_SALES_EXPORT_FAIL = "USER_SALES_EXPORT_FAIL";
export const DAILY_SALES_EXPORT_START = "DAILY_SALES_EXPORT_START";
export const DAILY_SALES_EXPORT_SUCCESS = "DAILY_SALES_EXPORT_SUCCESS";
export const DAILY_SALES_EXPORT_FAIL = "DAILY_SALES_EXPORT_FAIL";
export const TAX_COLLECTED_REPORT_START = "TAX_COLLECTED_REPORT_START";
export const TAX_COLLECTED_REPORT_SUCCESS = "TAX_COLLECTED_REPORT_SUCCESS";
export const TAX_COLLECTED_REPORT_FAIL = "TAX_COLLECTED_REPORT_FAIL";
export const TAX_COLLECTED_EXPORT_START = "TAX_COLLECTED_EXPORT_START";
export const TAX_COLLECTED_EXPORT_SUCCESS = "TAX_COLLECTED_EXPORT_SUCCESS";
export const TAX_COLLECTED_EXPORT_FAIL = "TAX_COLLECTED_EXPORT_FAIL";
export const GIFT_CARD_REPORT_START = "GIFT_CARD_REPORT_START";
export const GIFT_CARD_REPORT_SUCCESS = "GIFT_CARD_REPORT_SUCCESS";
export const GIFT_CARD_REPORT_FAIL = "GIFT_CARD_REPORT_FAIL";
export const GIFT_CARD_EXPORT_START = "GIFT_CARD_EXPORT_START";
export const GIFT_CARD_EXPORT_SUCCESS = "GIFT_CARD_EXPORT_SUCCESS";
export const GIFT_CARD_EXPORT_FAIL = "GIFT_CARD_EXPORT_FAIL";

export const INVOICE_HISTORY_REPORT_REQUEST = "INVOICE_HISTORY_REPORT_REQUEST";
export const INVOICE_HISTORY_REPORT_SUCCESS = "INVOICE_HISTORY_REPORT_SUCCESS";
export const INVOICE_HISTORY_REPORT_FAIL = "INVOICE_HISTORY_REPORT_FAIL";

export const INVOICE_HISTORY_EXPORT_REQUEST = "INVOICE_HISTORY_EXPORT_REQUEST";
export const INVOICE_HISTORY_EXPORT_SUCCESS = "INVOICE_HISTORY_EXPORT_SUCCESS";
export const INVOICE_HISTORY_EXPORT_FAIL = "INVOICE_HISTORY_EXPORT_FAIL";

export const INVOICE_RESET = "INVOICE_RESET";

export const BATCH_CLOSED_REPORT_START = "BATCH_CLOSED_REPORT_START";
export const BATCH_CLOSED_REPORT_SUCCESS = "BATCH_CLOSED_REPORT_SUCCESS";
export const BATCH_CLOSED_REPORT_FAIL = "BATCH_CLOSED_REPORT_FAIL";

export const BATCH_CLOSED_REPORT_EXPORT_START =
  "BATCH_CLOSED_REPORT_EXPORT_START";
export const BATCH_CLOSED_REPORT_EXPORT_SUCCESS =
  "BATCH_CLOSED_REPORT_EXPORT_SUCCESS";
export const BATCH_CLOSED_REPORT_EXPORT_FAIL =
  "BATCH_CLOSED_REPORT_EXPORT_FAIL";

export const BATCH_CLOSED_LIST_START = "BATCH_CLOSED_LIST_START";
export const BATCH_CLOSED_LIST_SUCCESS = "BATCH_CLOSED_LIST_SUCCESS";
export const BATCH_CLOSED_LIST_FAIL = "BATCH_CLOSED_LIST_FAIL";
export const SERVICE_REPORT_START = "SERVICE_REPORT_START";
export const SERVICE_REPORT_SUCCESS = "SERVICE_REPORT_SUCCESS";
export const SERVICE_REPORT_FAIL = "SERVICE_REPORT_FAIL";
export const SERVICE_EXPORT_START = "SERVICE_EXPORT_START";
export const SERVICE_EXPORT_SUCCESS = "SERVICE_EXPORT_SUCCESS";
export const SERVICE_EXPORT_FAIL = "SERVICE_EXPORT_FAIL";

/*****CURRENCY BILLS********/
export const CURRENCY_BILL_REQUEST = "CURRENCY_BILL_REQUEST";
export const CURRENCY_BILL_SUCCESS = "CURRENCY_BILL_SUCCESS";
export const CURRENCY_BILL_FAIL = "CURRENCY_BILL_FAIL";

export const CURRENCY_BILL_CREATE_REQUEST = "CURRENCY_BILL_CREATE_REQUEST";
export const CURRENCY_BILL_CREATE_SUCCESS = "CURRENCY_BILL_CREATE_SUCCESS";
export const CURRENCY_BILL_CREATE_FAIL = "CURRENCY_BILL_CREATE_FAIL";

export const CURRENCY_BILL_UPDATE_REQUEST = "CURRENCY_BILL_UPDATE_REQUEST";
export const CURRENCY_BILL_UPDATE_SUCCESS = "CURRENCY_BILL_UPDATE_SUCCESS";
export const CURRENCY_BILL_UPDATE_FAIL = "CURRENCY_BILL_UPDATE_FAIL";

export const CURRENCY_BILL_DELETE_REQUEST = "CURRENCY_BILL_DELETE_REQUEST";
export const CURRENCY_BILL_DELETE_SUCCESS = "CURRENCY_BILL_DELETE_SUCCESS";
export const CURRENCY_BILL_DELETE_FAIL = "CURRENCY_BILL_DELETE_FAIL";

export const CURRENCY_BILL_GET_DETAILS_REQUEST =
  "CURRENCY_BILL_GET_DETAILS_REQUEST";
export const CURRENCY_BILL_GET_DETAILS_SUCCESS =
  "CURRENCY_BILL_GET_DETAILS_SUCCESS";
export const CURRENCY_BILL_GET_DETAILS_FAIL = "CURRENCY_BILL_GET_DETAILS_FAIL";

export const ADD_CURRENCY_BILL_FILTER = "ADD_CURRENCY_BILL_FILTER";
export const DELETE_CURRENCY_BILL_FILTER = "DELETE_CURRENCY_BILL_FILTER";
export const CURRENCY_BILL_RESET = "CURRENCY_BILL_RESET";

/***** PRINTER SETTINGS ********/
export const PRINTER_LIST_REQUEST = "PRINTER_LIST_REQUEST";
export const PRINTER_LIST_SUCCESS = "PRINTER_LIST_SUCCESS";
export const PRINTER_LIST_FAIL = "PRINTER_LIST_FAIL";

export const PRINTER_CREATE_REQUEST = "PRINTER_CREATE_REQUEST";
export const PRINTER_CREATE_SUCCESS = "PRINTER_CREATE_SUCCESS";
export const PRINTER_CREATE_FAIL = "PRINTER_CREATE_FAIL";

export const PRINTER_DELETE_REQUEST = "PRINTER_DELETE_REQUEST";
export const PRINTER_DELETE_SUCCESS = "PRINTER_DELETE_SUCCESS";
export const PRINTER_DELETE_FAIL = "PRINTER_DELETE_FAIL";

export const PRINTER_UPDATE_REQUEST = "PRINTER_UPDATE_REQUEST";
export const PRINTER_UPDATE_SUCCESS = "PRINTER_UPDATE_SUCCESS";
export const PRINTER_UPDATE_FAIL = "PRINTER_UPDATE_FAIL";

export const PRINTER_DETAIL_REQUEST = "PRINTER_DETAIL_REQUEST";
export const PRINTER_DETAIL_SUCCESS = "PRINTER_DETAIL_SUCCESS";
export const PRINTER_DETAIL_FAIL = "PRINTER_DETAIL_FAIL";

export const DELETE_PRINTER_FILTER = "DELETE_PRINTER_FILTER";
export const ADD_PRINTER_FILTER = "ADD_PRINTER_FILTER";

export const PRINT_ADD_TO_QUEUE_REQUEST = "PRINT_ADD_TO_QUEUE_REQUEST";
export const PRINT_ADD_TO_QUEUE_SUCCESS = "PRINT_ADD_TO_QUEUE_SUCCESS";
export const PRINT_ADD_TO_QUEUE_FAIL = "PRINT_ADD_TO_QUEUE_FAIL";

export const PRINT_CLOUD_TEST_REQUEST = "PRINT_CLOUD_TEST_REQUEST";
export const PRINT_CLOUD_TEST_SUCCESS = "PRINT_CLOUD_TEST_SUCCESS";
export const PRINT_CLOUD_TEST_FAIL = "PRINT_CLOUD_TEST_FAIL";

export const PRINTER_SETTINGS_CREATE_REQUEST =
  "PRINTER_SETTINGS_CREATE_REQUEST";
export const PRINTER_SETTINGS_CREATE_SUCCESS =
  "PRINTER_SETTINGS_CREATE_SUCCESS";
export const PRINTER_SETTINGS_CREATE_FAIL = "PRINTER_SETTINGS_CREATE_FAIL";

export const PRINTER_SETTINGS_UPDATE_REQUEST =
  "PRINTER_SETTINGS_UPDATE_REQUEST";
export const PRINTER_SETTINGS_UPDATE_SUCCESS =
  "PRINTER_SETTINGS_UPDATE_SUCCESS";
export const PRINTER_SETTINGS_UPDATE_FAIL = "PRINTER_SETTINGS_UPDATE_FAIL";

export const PRINTER_SETTING_REQUEST = "PRINTER_SETTING_REQUEST";
export const PRINTER_SETTING_SUCCESS = "PRINTER_SETTING_SUCCESS";
export const PRINTER_SETTING_FAIL = "PRINTER_SETTING_FAIL";

export const PRINTER_SETTING_DETAIL_REQUEST = "PRINTER_SETTING_DETAIL_REQUEST";
export const PRINTER_SETTING_DETAIL_SUCCESS = "PRINTER_SETTING_DETAIL_SUCCESS";
export const PRINTER_SETTING_DETAIL_FAIL = "PRINTER_SETTING_DETAIL_FAIL";

export const PRINTER_SETTINGS_LIST_REQUEST = "PRINTER_SETTINGS_LIST_REQUEST";
export const PRINTER_SETTINGS_LIST_SUCCESS = "PRINTER_SETTINGS_LIST_SUCCESS";
export const PRINTER_SETTINGS_LIST_FAIL = "PRINTER_SETTINGS_LIST_FAIL";

export const PRINTER_SETTINGS_DELETE_REQUEST =
  "PRINTER_SETTINGS_DELETE_REQUEST";
export const PRINTER_SETTINGS_DELETE_SUCCESS =
  "PRINTER_SETTINGS_DELETE_SUCCESS";
export const PRINTER_SETTINGS_DELETE_FAIL = "PRINTER_SETTINGS_DELETE_FAIL";

export const DELETE_PRINTER_SETTING_FILTER = "DELETE_PRINTER_SETTING_FILTER";
export const ADD_PRINTER_SETTING_FILTER = "ADD_PRINTER_SETTING_FILTER";

export const PRINTER_MODEL_LIST_REQUEST = "PRINTER_MODEL_LIST_REQUEST";
export const PRINTER_MODEL_LIST_SUCCESS = "PRINTER_MODEL_LIST_SUCCESS";
export const PRINTER_MODEL_LIST_FAIL = "PRINTER_MODEL_LIST_FAIL";

export const PRINTER_PAPERSIZE_LIST_REQUEST = "PRINTER_PAPERSIZE_LIST_REQUEST";
export const PRINTER_PAPERSIZE_LIST_SUCCESS = "PRINTER_PAPERSIZE_LIST_SUCCESS";
export const PRINTER_PAPERSIZE_LIST_FAIL = "PRINTER_PAPERSIZE_LIST_FAIL";

/****** LABEL SETTINGS ******/

export const LABEL_SETTINGS_CREATE_REQUEST = "LABEL_SETTINGS_CREATE_REQUEST";
export const LABEL_SETTINGS_CREATE_SUCCESS = "LABEL_SETTINGS_CREATE_SUCCESS";
export const LABEL_SETTINGS_CREATE_FAIL = "LABEL_SETTINGS_CREATE_FAIL";

export const LABEL_SETTING_REQUEST = "LABEL_SETTING_REQUEST";
export const LABEL_SETTING_SUCCESS = "LABEL_SETTING_SUCCESS";
export const LABEL_SETTING_FAIL = "LABEL_SETTING_FAIL";

export const LABEL_SETTING_DETAIL_REQUEST = "LABEL_SETTING_DETAIL_REQUEST";
export const LABEL_SETTING_DETAIL_SUCCESS = "LABEL_SETTING_DETAIL_SUCCESS";
export const LABEL_SETTING_DETAIL_FAIL = "LABEL_SETTING_DETAIL_FAIL";

export const LABEL_SETTINGS_DELETE_REQUEST = "LABEL_SETTINGS_DELETE_REQUEST";
export const LABEL_SETTINGS_DELETE_SUCCESS = "LABEL_SETTINGS_DELETE_SUCCESS";
export const LABEL_SETTINGS_DELETE_FAIL = "LABEL_SETTINGS_DELETE_FAIL";

export const DELETE_LABEL_SETTING_FILTER = "DELETE_LABEL_SETTING_FILTER";
export const ADD_LABEL_SETTING_FILTER = "ADD_LABEL_SETTING_FILTER";

/***** EOD RECONCILIATION ********/
export const EOD_RECONCILE_REQUEST = "EOD_RECONCILE_REQUEST";
export const EOD_RECONCILE_SUCCESS = "EOD_RECONCILE_SUCCESS";
export const EOD_RECONCILE_FAIL = "EOD_RECONCILE_FAIL";

export const EOD_RECONCILE_CREATE_REQUEST = "EOD_RECONCILE_CREATE_REQUEST";
export const EOD_RECONCILE_CREATE_SUCCESS = "EOD_RECONCILE_CREATE_SUCCESS";
export const EOD_RECONCILE_CREATE_FAIL = "EOD_RECONCILE_CREATE_FAIL";

export const EOD_RECONCILE_GET_DETAILS_REQUEST =
  "EOD_RECONCILE_GET_DETAILS_REQUEST";
export const EOD_RECONCILE_GET_DETAILS_SUCCESS =
  "EOD_RECONCILE_GET_DETAILS_SUCCESS";
export const EOD_RECONCILE_GET_DETAILS_FAIL = "EOD_RECONCILE_GET_DETAILS_FAIL";

export const ADD_EOD_RECONCILE_FILTER = "ADD_EOD_RECONCILE_FILTER";
export const DELETE_EOD_RECONCILE_FILTER = "DELETE_EOD_RECONCILE_FILTER";
export const EOD_RECONCILE_RESET = "EOD_RECONCILE_RESET";

export const EOD_RECONCILE_UPDATE_REQUEST = "EOD_RECONCILE_UPDATE_REQUEST";
export const EOD_RECONCILE_UPDATE_SUCCESS = "EOD_RECONCILE_UPDATE_SUCCESS";
export const EOD_RECONCILE_UPDATE_FAIL = "EOD_RECONCILE_UPDATE_FAIL";

export const EOD_RECONCILE_DELETE_REQUEST = "EOD_RECONCILE_DELETE_REQUEST";
export const EOD_RECONCILE_DELETE_SUCCESS = "EOD_RECONCILE_DELETE_SUCCESS";
export const EOD_RECONCILE_DELETE_FAIL = "EOD_RECONCILE_DELETE_FAIL";

export const EOD_RECONCILE_SO_REQUEST = "EOD_RECONCILE_SO_REQUEST";
export const EOD_RECONCILE_SO_SUCCESS = "EOD_RECONCILE_SO_SUCCESS";
export const EOD_RECONCILE_SO_FAIL = "EOD_RECONCILE_SO_FAIL";

export const EOD_RECONCILE_LAST_DRAWER_REQUEST =
  "EOD_RECONCILE_LAST_DRAWER_REQUEST";
export const EOD_RECONCILE_LAST_DRAWER_SUCCESS =
  "EOD_RECONCILE_LAST_DRAWER_SUCCESS";
export const EOD_RECONCILE_LAST_DRAWER_FAIL = "EOD_RECONCILE_LAST_DRAWER_FAIL";

export const EOD_RECON_CASH_GET_DETAILS_REQUEST =
  "EOD_RECON_CASH_GET_DETAILS_REQUEST";
export const EOD_RECON_CC_GET_DETAILS_REQUEST =
  "EOD_RECON_CC_GET_DETAILS_REQUEST";
export const EOD_RECON_CHECK_GET_DETAILS_REQUEST =
  "EOD_RECON_CHECK_GET_DETAILS_REQUEST";
export const EOD_RECON_DEBIT_GET_DETAILS_REQUEST =
  "EOD_RECON_DEBIT_GET_DETAILS_REQUEST";
export const EOD_RECON_GIFTCARD_GET_DETAILS_REQUEST =
  "EOD_RECON_GIFTCARD_GET_DETAILS_REQUEST";

export const EOD_RECON_CASH_GET_DETAILS_SUCCESS =
  "EOD_RECON_CASH_GET_DETAILS_SUCCESS";
export const EOD_RECON_CC_GET_DETAILS_SUCCESS =
  "EOD_RECON_CC_GET_DETAILS_SUCCESS";
export const EOD_RECON_CHECK_GET_DETAILS_SUCCESS =
  "EOD_RECON_CHECK_GET_DETAILS_SUCCESS";
export const EOD_RECON_DEBIT_GET_DETAILS_SUCCESS =
  "EOD_RECON_DEBIT_GET_DETAILS_SUCCESS";
export const EOD_RECON_GIFTCARD_GET_DETAILS_SUCCESS =
  "EOD_RECON_GIFTCARD_GET_DETAILS_SUCCESS";

/***** EOD MEMO ********/
export const MEMO_REQUEST = "MEMO_REQUEST";
export const MEMO_SUCCESS = "MEMO_SUCCESS";
export const MEMO_FAIL = "MEMO_FAIL";

/******** reset RESET_VARIANT_OPTION_PRODUCT *******/
export const RESET_VARIANT_OPTION_PRODUCT = "RESET_VARIANT_OPTION_PRODUCT";

/**** SMS SETTINGS *****/
export const SMS_SETTINGS_REQUEST = "SMS_SETTINGS_REQUEST";
export const SMS_SETTINGS_SUCCESS = "SMS_SETTINGS_SUCCESS";
export const SMS_SETTINGS_FAIL = "SMS_SETTINGS_FAIL";
export const SMS_SETTINGS_CREATE_REQUEST = "SMS_SETTINGS_CREATE_REQUEST";
export const SMS_SETTINGS_CREATE_SUCCESS = "SMS_SETTINGS_CREATE_SUCCESS";
export const SMS_SETTINGS_CREATE_FAIL = "SMS_SETTINGS_CREATE_FAIL";
export const SMS_SETTINGS_UPDATE_REQUEST = "SMS_SETTINGS_UPDATE_REQUEST";
export const SMS_SETTINGS_UPDATE_SUCCESS = "SMS_SETTINGS_UPDATE_SUCCESS";
export const SMS_SETTINGS_UPDATE_FAIL = "SMS_SETTINGS_UPDATE_FAIL";
export const SMS_SETTINGS_DELETE_REQUEST = "SMS_SETTINGS_DELETE_REQUEST";
export const SMS_SETTINGS_DELETE_SUCCESS = "SMS_SETTINGS_DELETE_SUCCESS";
export const SMS_SETTINGS_DELETE_FAIL = "SMS_SETTINGS_DELETE_FAIL";
export const SMS_SETTINGS_GET_DETAILS_REQUEST =
  "SMS_SETTINGS_GET_DETAILS_REQUEST";
export const SMS_SETTINGS_GET_DETAILS_SUCCESS =
  "SMS_SETTINGS_GET_DETAILS_SUCCESS";
export const SMS_SETTINGS_GET_DETAILS_FAIL = "SMS_SETTINGS_GET_DETAILS_FAIL";
export const ADD_SMS_SETTINGS_FILTER = "ADD_SMS_SETTINGS_FILTER";
export const DELETE_SMS_SETTINGS_FILTER = "DELETE_SMS_SETTINGS_FILTER";
export const SMS_SETTINGS_RESET = "SMS_SETTINGS_RESET";
export const SMS_CONFIG_VALIDATE_REQUEST = "SMS_CONFIG_VALIDATE_REQUEST";
export const SMS_CONFIG_VALIDATE_SUCCESS = "SMS_CONFIG_VALIDATE_SUCCESS";
export const SMS_CONFIG_VALIDATE_FAIL = "SMS_CONFIG_VALIDATE_FAIL";

/***** EMAIL SETTINGS *****/
export const EMAIL_SETTINGS_REQUEST = "EMAIL_SETTINGS_REQUEST";
export const EMAIL_SETTINGS_SUCCESS = "EMAIL_SETTINGS_SUCCESS";
export const EMAIL_SETTINGS_FAIL = "EMAIL_SETTINGS_FAIL";
export const EMAIL_SETTINGS_CREATE_REQUEST = "EMAIL_SETTINGS_CREATE_REQUEST";
export const EMAIL_SETTINGS_CREATE_SUCCESS = "EMAIL_SETTINGS_CREATE_SUCCESS";
export const EMAIL_SETTINGS_CREATE_FAIL = "EMAIL_SETTINGS_CREATE_FAIL";
export const EMAIL_SETTINGS_UPDATE_REQUEST = "EMAIL_SETTINGS_UPDATE_REQUEST";
export const EMAIL_SETTINGS_UPDATE_SUCCESS = "EMAIL_SETTINGS_UPDATE_SUCCESS";
export const EMAIL_SETTINGS_UPDATE_FAIL = "EMAIL_SETTINGS_UPDATE_FAIL";
export const EMAIL_SETTINGS_DELETE_REQUEST = "EMAIL_SETTINGS_DELETE_REQUEST";
export const EMAIL_SETTINGS_DELETE_SUCCESS = "EMAIL_SETTINGS_DELETE_SUCCESS";
export const EMAIL_SETTINGS_DELETE_FAIL = "EMAIL_SETTINGS_DELETE_FAIL";
export const EMAIL_SETTINGS_GET_DETAILS_REQUEST =
  "EMAIL_SETTINGS_GET_DETAILS_REQUEST";
export const EMAIL_SETTINGS_GET_DETAILS_SUCCESS =
  "EMAIL_SETTINGS_GET_DETAILS_SUCCESS";
export const EMAIL_SETTINGS_GET_DETAILS_FAIL =
  "EMAIL_SETTINGS_GET_DETAILS_FAIL";
export const ADD_EMAIL_SETTINGS_FILTER = "ADD_EMAIL_SETTINGS_FILTER";
export const DELETE_EMAIL_SETTINGS_FILTER = "DELETE_EMAIL_SETTINGS_FILTER";
export const EMAIL_SETTINGS_RESET = "EMAIL_SETTINGS_RESET";
export const EMAIL_CONFIG_VALIDATE_REQUEST = "EMAIL_CONFIG_VALIDATE_REQUEST";
export const EMAIL_CONFIG_VALIDATE_SUCCESS = "EMAIL_CONFIG_VALIDATE_SUCCESS";
export const EMAIL_CONFIG_VALIDATE_FAIL = "EMAIL_CONFIG_VALIDATE_FAIL";

/***** TIPS SETTINGS *****/
export const TIPS_LIST_REQUEST = "TIPS_LIST_REQUEST";
export const TIPS_LIST_SUCCESS = "TIPS_LIST_SUCCESS";
export const TIPS_LIST_FAIL = "TIPS_LIST_FAIL";

export const TIPS_SET_REQUEST = "TIPS_SET_REQUEST";
export const TIPS_SET_SUCCESS = "TIPS_SET_SUCCESS";
export const TIPS_SET_FAIL = "TIPS_SET_FAIL";

/***** RECEIPT *****/
export const SEND_RECEIPT_REQUEST = "SEND_RECEIPT_REQUEST";
export const SEND_RECEIPT_SUCCESS = "SEND_RECEIPT_SUCCESS";
export const SEND_RECEIPT_FAIL = "SEND_RECEIPT_FAIL";

export const SEND_PDF_RECEIPT_REQUEST = "SEND_PDF_RECEIPT_REQUEST";
export const SEND_PDF_RECEIPT_SUCCESS = "SEND_PDF_RECEIPT_SUCCESS";
export const SEND_PDF_RECEIPT_FAIL = "SEND_PDF_RECEIPT_FAIL";

/***** Branch *****/
export const BRANCH_RESET = "BRANCH_RESET";
export const BRANCH_REQUEST = "BRANCH_REQUEST";
export const BRANCH_SUCCESS = "BRANCH_SUCCESS";
export const BRANCH_FAIL = "BRANCH_FAIL";

export const ALL_BRANCH_REQUEST = "ALL_BRANCH_REQUEST";
export const ALL_BRANCH_SUCCESS = "ALL_BRANCH_SUCCESS";
export const ALL_BRANCH_FAIL = "ALL_BRANCH_FAIL";

export const BRANCH_CREATE_REQUEST = "BRANCH_CREATE_REQUEST";
export const BRANCH_CREATE_SUCCESS = "BRANCH_CREATE_SUCCESS";
export const BRANCH_CREATE_FAIL = "BRANCH_CREATE_FAIL";

export const BRANCH_UPDATE_REQUEST = "BRANCH_UPDATE_REQUEST";
export const BRANCH_UPDATE_SUCCESS = "BRANCH_UPDATE_SUCCESS";
export const BRANCH_UPDATE_FAIL = "BRANCH_UPDATE_FAIL";

export const BRANCH_DELETE_REQUEST = "BRANCH_DELETE_REQUEST";
export const BRANCH_DELETE_SUCCESS = "BRANCH_DELETE_SUCCESS";
export const BRANCH_DELETE_FAIL = "BRANCH_DELETE_FAIL";

export const BRANCH_GET_DETAILS_REQUEST = "BRANCH_GET_DETAILS_REQUEST";
export const BRANCH_GET_DETAILS_SUCCESS = "BRANCH_GET_DETAILS_SUCCESS";
export const BRANCH_GET_DETAILS_FAIL = "BRANCH_GET_DETAILS_FAIL";

export const ADD_BRANCH_FILTER = "ADD_BRANCH_FILTER";
export const DELETE_BRANCH_FILTER = "DELETE_BRANCH_FILTER";

/***** Sales Agent *****/
export const SALES_AGENT_RESET = "SALES_AGENT_RESET";
export const SALES_AGENT_REQUEST = "SALES_AGENT_REQUEST";
export const SALES_AGENT_SUCCESS = "SALES_AGENT_SUCCESS";
export const SALES_AGENT_FAIL = "SALES_AGENT_FAIL";

export const ALL_SALES_AGENT_REQUEST = "ALL_SALES_AGENT_REQUEST";
export const ALL_SALES_AGENT_SUCCESS = "ALL_SALES_AGENT_SUCCESS";
export const ALL_SALES_AGENT_FAIL = "ALL_SALES_AGENT_FAIL";

export const SALES_AGENT_CREATE_REQUEST = "SALES_AGENT_CREATE_REQUEST";
export const SALES_AGENT_CREATE_SUCCESS = "SALES_AGENT_CREATE_SUCCESS";
export const SALES_AGENT_CREATE_FAIL = "SALES_AGENT_CREATE_FAIL";

export const SALES_AGENT_UPDATE_REQUEST = "SALES_AGENT_UPDATE_REQUEST";
export const SALES_AGENT_UPDATE_SUCCESS = "SALES_AGENT_UPDATE_SUCCESS";
export const SALES_AGENT_UPDATE_FAIL = "SALES_AGENT_UPDATE_FAIL";

export const SALES_AGENT_DELETE_REQUEST = "SALES_AGENT_DELETE_REQUEST";
export const SALES_AGENT_DELETE_SUCCESS = "SALES_AGENT_DELETE_SUCCESS";
export const SALES_AGENT_DELETE_FAIL = "SALES_AGENT_DELETE_FAIL";

export const SALES_AGENT_GET_DETAILS_REQUEST =
  "SALES_AGENT_GET_DETAILS_REQUEST";
export const SALES_AGENT_GET_DETAILS_SUCCESS =
  "SALES_AGENT_GET_DETAILS_SUCCESS";
export const SALES_AGENT_GET_DETAILS_FAIL = "SALES_AGENT_GET_DETAILS_FAIL";

export const ADD_SALES_AGENT_FILTER = "ADD_SALES_AGENT_FILTER";
export const DELETE_SALES_AGENT_FILTER = "DELETE_SALES_AGENT_FILTER";

export const POS_USER_VIEW_REQUEST = "POS_USER_VIEW_REQUEST";
export const POS_USER_VIEW_SAVE = "POS_USER_VIEW_SAVE";
export const POS_USER_VIEW_DELETE = "POS_USER_VIEW_DELETE";

export const POS_USER_PAYMNET_TERMINAL_REQUEST =
  "POS_USER_PAYMNET_TERMINAL_REQUEST";
export const POS_USER_PAYMNET_TERMINAL_SAVE = "POS_PAYMNET_TERMINAL_SAVE";
export const POS_USER_PAYMNET_TERMINAL_DELETE =
  "POS_USER_PAYMNET_TERMINAL_DELETE";

export const SAVE_TIME_CARD_REPORT_DETAILS = "SAVE_TIME_CARD_REPORT_DETAILS";
export const UPDATE_TIME_CARD_FILTERS = "UPDATE_TIME_CARD_FILTERS";
export const TIME_CARD_REPORT_DETAILS_EXPORT_SUCCESS =
  "TIME_CARD_REPORT_DETAILS_EXPORT_SUCCESS";
export const TIME_CARD_REPORT_DETAILS_EXPORT_FAIL =
  "TIME_CARD_REPORT_DETAILS_EXPORT_FAIL";

export const GET_TIME_CARD_USERS = "GET_TIME_CARD_USERS";
export const GET_TIME_CARD_USERS_SUCCESS = "GET_TIME_CARD_USERS_SUCCESS";
export const GET_TIME_CARD_USERS_FAIL = "GET_TIME_CARD_USERS_FAIL";

export const SAVE_LOGIN_TIME_LOG = "SAVE_LOGIN_TIME_LOG";
export const SAVE_LOGIN_TIME_LOG_FAIL = "SAVE_LOGIN_TIME_LOG_FAIL";
export const SAVE_LOGIN_TIME_LOG_SUCCESS = "SAVE_LOGIN_TIME_LOG_SUCCESS";
export const SAVE_LOGIN_TIME_LOG_SUCCESS_UPDATE =
  "SAVE_LOGIN_TIME_LOG_SUCCESS_UPDATE";

export const GET_TIME_CARD_REPORT_DETAILS = "GET_TIME_CARD_REPORT_DETAILS";
export const GET_TIME_CARD_REPORT_DETAILS_SUCCESS =
  "GET_TIME_CARD_REPORT_DETAILS_SUCCESS";
export const GET_TIME_CARD_REPORT_DETAILS_FAIL =
  "GET_TIME_CARD_REPORT_DETAILS_FAIL";

export const UPDATE_LOGIN_TIME_LOG = "UPDATE_LOGIN_TIME_LOG";
export const UPDATE_LOGIN_TIME_LOG_SUCCESS = "UPDATE_LOGIN_TIME_LOG_SUCCESS";
export const UPDATE_LOGIN_TIME_LOG_FAIL = "UPDATE_LOGIN_TIME_LOG_FAIL";

export const GET_USER_CLOCK_HOURS = "GET_USER_CLOCK_HOURS";
export const GET_USER_CLOCK_HOURS_SUCCESS = "GET_USER_CLOCK_HOURS_SUCCESS";
export const GET_USER_CLOCK_HOURS_FAIL = "GET_USER_CLOCK_HOURS_FAIL";

export const GET_LABOUR_COST_REPORTS = "GET_LABOUR_COST_REPORTS";
export const GET_LABOUR_COST_REPORTS_SUCCESS =
  "GET_LABOUR_COST_REPORTS_SUCCESS";
export const GET_LABOUR_COST_REPORTS_FAIL = "GET_LABOUR_COST_REPORTS_FAIL";
export const GET_LABOUR_COST_REPORTS_EXPORT_SUCCESS =
  "GET_LABOUR_COST_REPORTS_EXPORT_SUCCESS";
export const GET_LABOUR_COST_REPORTS_EXPORT_FAIL =
  "GET_LABOUR_COST_REPORTS_EXPORT_FAIL";
export const GET_LABOUR_COST_USERS = "GET_LABOUR_COST_USERS";
export const GET_LABOUR_COST_USERS_FAIL = "GET_LABOUR_COST_USERS_FAIL";
export const GET_LABOUR_COST_USERS_SUCCESS = "GET_LABOUR_COST_USERS_SUCCESS";
export const UPDATE_LABOUR_COST_FILTERS = "UPDATE_LABOUR_COST_FILTERS";
export const RESET_LABOUR_COST = "RESET_LABOUR_COST";
export const OP_PRODUCT_GET_DETAILS_REQUEST = "OP_PRODUCT_GET_DETAILS_REQUEST";
/*****LMS CATEGORY********/
export const REQUEST_UNIVERSITY_USER = "REQUEST_UNIVERSITY_USER";
export const SUCCESS_UNIVERSITY_USER = "SUCCESS_UNIVERSITY_USER";
export const FAIL_UNIVERSITY_USER = "FAIL_UNIVERSITY_USER";

export const LMS_CATEGORY_REQUEST = "LMS_CATEGORY_REQUEST";
export const LMS_CATEGORY_CREATE_REQUEST = "LMS_CATEGORY_CREATE_REQUEST";
export const LMS_CATEGORY_GET_DETAIL_REQUEST =
  "LMS_CATEGORY_GET_DETAIL_REQUEST";
export const LMS_CATEGORY_DELETE_REQUEST = "LMS_CATEGORY_DELETE_REQUEST";
export const ADD_LMS_CATEGORY_FILTER = "ADD_LMS_CATEGORY_FILTER";
export const DELETE_LMS_CATEGORY_FILTER = "DELETE_LMS_CATEGORY_FILTER";
export const LMS_CATEGORY_UPDATE_REQUEST = "LMS_CATEGORY_UPDATE_REQUEST";

export const LMS_CATEGORY_LIST_REQUEST = "LMS_CATEGORY_LIST_REQUEST";
export const LMS_CATEGORY_SUCCESS = "LMS_CATEGORY_SUCCESS";
export const LMS_CATEGORY_FAIL = "LMS_CATEGORY_FAIL";
export const LMS_CATEGORY_RESET_LIST = "LMS_CATEGORY_RESET_LIST";

export const LMS_CATEGORY_CREATE_SUCCESS = "LMS_CATEGORY_CREATE_SUCCESS";
export const LMS_CATEGORY_CREATE_FAIL = "LMS_CATEGORY_CREATE_FAIL";

export const LMS_CATEGORY_UPDATE_SUCCESS = "LMS_CATEGORY_UPDATE_SUCCESS";
export const LMS_CATEGORY_UPDATE_FAIL = "LMS_CATEGORY_UPDATE_FAIL";

export const LMS_CATEGORY_DELETE_SUCCESS = "LMS_CATEGORY_DELETE_SUCCESS";
export const LMS_CATEGORY_DELETE_FAIL = "LMS_CATEGORY_DELETE_FAIL";

export const LMS_CATEGORY_GET_DETAIL_SUCCESS =
  "LMS_CATEGORY_GET_DETAIL_SUCCESS";
export const LMS_CATEGORY_GET_DETAIL_FAIL = "LMS_CATEGORY_GET_DETAIL_FAIL";

export const LMS_CATEGORY_CONTENT_REQUEST = "LMS_CATEGORY_CONTENT_REQUEST";
export const LMS_CATEGORY_CONTENT_SUCCESS = "LMS_CATEGORY_CONTENT_SUCCESS";
export const LMS_CATEGORY_CONTENT_FAIL = "LMS_CATEGORY_CONTENT_FAIL";
/*****LMS VIDEO********/
export const LMS_VDO_REQUEST = "LMS_VDO_REQUEST";
export const LMS_VDO_SUCCESS = "LMS_VDO_SUCCESS";
export const LMS_VDO_FAIL = "LMS_VDO_FAIL";

export const LMS_VDO_CREATE_REQUEST = "LMS_VDO_CREATE_REQUEST";
export const LMS_VDO_CREATE_SUCCESS = "LMS_VDO_CREATE_SUCCESS";
export const LMS_VDO_CREATE_FAIL = "LMS_VDO_CREATE_FAIL";

export const LMS_VDO_UPDATE_REQUEST = "LMS_VDO_UPDATE_REQUEST";
export const LMS_VDO_UPDATE_SUCCESS = "LMS_VDO_UPDATE_SUCCESS";
export const LMS_VDO_UPDATE_FAIL = "LMS_VDO_UPDATE_FAIL";

export const LMS_VDO_DELETE_REQUEST = "LMS_VDO_DELETE_REQUEST";
export const LMS_VDO_DELETE_SUCCESS = "LMS_VDO_DELETE_SUCCESS";
export const LMS_VDO_DELETE_FAIL = "LMS_VDO_DELETE_FAIL";

export const LMS_VDO_GET_REQUEST = "LMS_VDO_GET_REQUEST";
export const LMS_VDO_GET_SUCCESS = "LMS_VDO_GET_SUCCESS";
export const LMS_VDO_GET_FAIL = "LMS_VDO_GET_FAIL";

export const ADD_LMS_VDO_FILTER = "ADD_LMS_VDO_FILTER";
export const DELETE_LMS_VDO_FILTER = "DELETE_LMS_VDO_FILTER";
export const RESET_LMS_VDO_DATA = "RESET_LMS_VDO_DATA";

export const LMS_UNIVERSITY_MODULE_REQUEST = "LMS_UNIVERSITY_MODULE_REQUEST";
export const LMS_UNIVERSITY_MODULE_SUCCESS = "LMS_UNIVERSITY_MODULE_SUCCESS";
export const LMS_UNIVERSITY_MODULE_FAIL = "LMS_UNIVERSITY_MODULE_FAIL";

export const GET_USER_BY_TYPE_REQUEST = "GET_USER_BY_TYPE_REQUEST";
export const GET_USER_BY_TYPE_SUCCESS = "GET_USER_BY_TYPE_SUCCESS";
export const GET_USER_BY_TYPE_FAIL = "GET_USER_BY_TYPE_FAIL";

/* Action type for combo group */
export const LIST_COMBO_GROUP_REQUEST = "LIST_COMBO_GROUP_REQUEST";
export const LIST_COMBO_GROUP_SUCCESS = "LIST_COMBO_GROUP_SUCCESS";
export const LIST_COMBO_GROUP_FAIL = "LIST_COMBO_GROUP_FAIL";

export const ADD_COMBO_GROUP_REQUEST = "ADD_COMBO_GROUP_REQUEST";
export const ADD_COMBO_GROUP_SUCCESS = "ADD_COMBO_GROUP_SUCCESS";
export const ADD_COMBO_GROUP_FAIL = "ADD_COMBO_GROUP_FAIL";
/* Action type for combo group */
export const LMS_ACTIVITY_REPORTS_REQUEST = "LMS_ACTIVITY_REPORTS_REQUEST";
export const LMS_ACTIVITY_REPORTS_SUCCESS = "LMS_ACTIVITY_REPORTS_SUCCESS";
export const LMS_ACTIVITY_REPORTS_FAIL = "LMS_ACTIVITY_REPORTS_FAIL";
export const LMS_ACTIVITY_USERS_REQUEST = "LMS_ACTIVITY_USERS_REQUEST";
export const LMS_ACTIVITY_USERS_SUCCESS = "LMS_ACTIVITY_USERS_SUCCESS";
export const LMS_ACTIVITY_USERS_FAIL = "LMS_ACTIVITY_USERS_FAIL";
export const LMS_ACTIVITY_REPORT_EXPORT_SUCCESS =
  "LMS_ACTIVITY_REPORT_EXPORT_SUCCESS";
export const LMS_ACTIVITY_REPORT_EXPORT_FAIL =
  "LMS_ACTIVITY_REPORT_EXPORT_FAIL";

export const GET_GIFT_CARD_BALANCE = "GET_GIFT_CARD_BALANCE";
export const RESET_GIFT_CARD_BALANCE = "RESET_GIFT_CARD_BALANCE";
export const GET_GIFT_CARD_BALANCE_SUCCESS = "GET_GIFT_CARD_BALANCE_SUCCESS";
export const GET_GIFT_CARD_BALANCE_FAIL = "GET_GIFT_CARD_BALANCE_FAIL";

export const GET_GIFT_CARD_LIST = "GET_GIFT_CARD_LIST";
export const GET_GIFT_CARD_LIST_SUCCESS = "GET_GIFT_CARD_LIST_SUCCESS";
export const GET_GIFT_CARD_LIST_FAIL = "GET_GIFT_CARD_LIST_FAIL";
export const MENU_PRODUCT_REQUEST = "MENU_PRODUCT_REQUEST";
export const MENU_PRODUCT_SUCCESS = "MENU_PRODUCT_SUCCESS";
export const MENU_PRODUCT_FAIL = "MENU_PRODUCT_FAIL";

export const MENU_GET_ALL_REQUEST = "MENU_GET_ALL_REQUEST";
export const MENU_GET_ALL_SUCCESS = "MENU_GET_ALL_SUCCESS";
export const MENU_GET_ALL_FAIL = "MENU_GET_ALL_FAIL";

export const MENU_GET_INDV_REQUEST = "MENU_GET_INDV_REQUEST";
export const MENU_GET_INDV_SUCCESS = "MENU_GET_INDV_SUCCESS";
export const MENU_GET_INDV_FAIL = "MENU_GET_INDV_FAIL";

export const MENU_PRODUCT_CREATE_REQUEST = "MENU_PRODUCT_CREATE_REQUEST";
export const MENU_PRODUCT_CREATE_SUCCESS = "MENU_PRODUCT_CREATE_SUCCESS";
export const MENU_PRODUCT_CREATE_FAIL = "MENU_PRODUCT_CREATE_FAIL";

export const MENU_PRODUCT_GET_REQUEST = "MENU_PRODUCT_GET_REQUEST";
export const MENU_PRODUCT_GET_SUCCESS = "MENU_PRODUCT_GET_SUCCESS";
export const MENU_PRODUCT_GET_FAIL = "MENU_PRODUCT_GET_FAIL";
export const MENU_PRODUCT_RESET_LIST = "MENU_PRODUCT_RESET_LIST";

export const MENU_PRODUCT_UPDATE_REQUEST = "MENU_PRODUCT_UPDATE_REQUEST";
export const MENU_PRODUCT_UPDATE_SUCCESS = "MENU_PRODUCT_UPDATE_SUCCESS";
export const MENU_PRODUCT_UPDATE_FAIL = "MENU_PRODUCT_UPDATE_FAIL";

export const MENU_PRODUCT_DELETE_REQUEST = "MENU_PRODUCT_DELETE_REQUEST";
export const MENU_PRODUCT_DELETE_SUCCESS = "MENU_PRODUCT_DELETE_SUCCESS";
export const MENU_PRODUCT_DELETE_FAIL = "MENU_PRODUCT_DELETE_FAIL";

export const MENU_SEARCH_ALL_REQUEST = "MENU_SEARCH_ALL_REQUEST";
export const MENU_SEARCH_ALL_SUCCESS = "MENU_SEARCH_ALL_SUCCESS";
export const MENU_SEARCH_ALL_FAIL = "MENU_SEARCH_ALL_FAIL";

export const MENU_INDIVIDUAL_PRODUCT_REQUEST =
  "MENU_INDIVIDUAL_PRODUCT_REQUEST";
export const MENU_INDIVIDUAL_PRODUCT_SUCCESS =
  "MENU_INDIVIDUAL_PRODUCT_SUCCESS";
export const MENU_INDIVIDUAL_PRODUCT_FAIL = "MENU_INDIVIDUAL_PRODUCT_FAIL";

/* Action type for Membership */
export const MEMBERSHIP_REPORT_START = "MEMBERSHIP_REPORT_START";
export const MEMBERSHIP_REPORT_SUCCESS = "MEMBERSHIP_REPORT_SUCCESS";
export const MEMBERSHIP_REPORT_FAIL = "MEMBERSHIP_REPORT_FAIL";
export const MEMBERSHIP_EXPORT_START = "MEMBERSHIP_EXPORT_START";
export const MEMBERSHIP_EXPORT_SUCCESS = "MEMBERSHIP_EXPORT_SUCCESS";
export const MEMBERSHIP_EXPORT_FAIL = "MEMBERSHIP_EXPORT_FAIL";
export const MEMBERSHIP_DETAILS_START = "MEMBERSHIP_DETAILS_START";
export const MEMBERSHIP_DETAILS_SUCCESS = "MEMBERSHIP_DETAILS_SUCCESS";
export const MEMBERSHIP_DETAILS_FAIL = "MEMBERSHIP_DETAILS_FAIL";
export const MEMBERSHIP_UPDATE_START = "MEMBERSHIP_UPDATE_START";
export const MEMBERSHIP_UPDATE_SUCCESS = "MEMBERSHIP_UPDATE_SUCCESS";
export const MEMBERSHIP_UPDATE_FAIL = "MEMBERSHIP_UPDATE_FAIL";
export const MEMBERSHIP_TERMINATE_START = "MEMBERSHIP_TERMINATE_START";
export const MEMBERSHIP_TERMINATE_SUCCESS = "MEMBERSHIP_TERMINATE_SUCCESS";
export const MEMBERSHIP_TERMINATE_FAIL = "MEMBERSHIP_TERMINATE_FAIL";
export const MEMBERSHIP_SAVEVAULT_START = "MEMBERSHIP_SAVEVAULT_START";
export const MEMBERSHIP_SAVEVAULT_SUCCESS = "MEMBERSHIP_SAVEVAULT_SUCCESS";
export const MEMBERSHIP_SAVEVAULT_FAIL = "MEMBERSHIP_SAVEVAULT_FAIL";

export const REQUEST_CRM_TRAINING_CONTENT = "REQUEST_CRM_TRAINING_CONTENT";
export const SUCCESS_CRM_TRAINING_CONTENT = "SUCCESS_CRM_TRAINING_CONTENT";
export const FAIL_CRM_TRAINING_CONTENT = "FAIL_CRM_TRAINING_CONTENT";

/* Action type for Training Documents */
export const REQUEST_TRAINING_VIDEOS = "REQUEST_TRAINING_VIDEOS";
export const SUCCESS_TRAINING_VIDEOS = "SUCCESS_TRAINING_VIDEOS";
export const FAIL_TRAINING_VIDEOS = "FAIL_TRAINING_VIDEOS";
export const REQUEST_TRAINING_DOCUMENTS = "REQUEST_TRAINING_DOCUMENTS";
export const SUCCESS_TRAINING_DOCUMENTS = "SUCCESS_TRAINING_DOCUMENTS";
export const FAIL_TRAINING_DOCUMENTS = "FAIL_TRAINING_DOCUMENTS";

/* Action type for membership terms and conditions */
export const TANDCLINK_SUCCESS = "TANDCLINK_SUCCESS";
export const TANDCLINK_REQUEST = "TANDCLINK_REQUEST";
export const TANDCLINK_FAIL = "TANDCLINK_FAIL";
export const M_TANDC_STATUS_UPDATE_REQUEST = "M_TANDC_STATUS_UPDATE_REQUEST";
export const M_TANDC_STATUS_UPDATE_SUCCESS = "M_TANDC_STATUS_UPDATE_SUCCESS";
export const M_TANDC_STATUS_UPDATE_FAIL = "M_TANDC_STATUS_UPDATE_FAIL";
export const SPLIT_SALES_ORDER_REQUEST = "SPLIT_SALES_ORDER_REQUEST";
export const SPLIT_SALES_ORDER_SUCCESS = "SPLIT_SALES_ORDER_SUCCESS";
export const SPLIT_SALES_ORDER_FAIL = "SPLIT_SALES_ORDER_FAIL";

export const SPLIT_SALES_ORDER_GET_REQUEST = "SPLIT_SALES_ORDER_GET_REQUEST";
export const SPLIT_SALES_ORDER_GET_SUCCESS = "SPLIT_SALES_ORDER_GET_SUCCESS";
export const SPLIT_SALES_ORDER_GET_FAIL = "SPLIT_SALES_ORDER_GET_FAIL";

/* Action type for Food Table */
export const FOOD_TABLE_LIST_REQUEST = "FOOD_TABLE_LIST_REQUEST";
export const FOOD_TABLE_SUCCESS = "FOOD_TABLE_SUCCESS";
export const FOOD_TABLE_FAIL = "FOOD_TABLE_FAIL";

export const FOOD_TABLE_CREATE_REQUEST = "FOOD_TABLE_CREATE_REQUEST";
export const FOOD_TABLE_CREATE_SUCCESS = "FOOD_TABLE_CREATE_SUCCESS";

export const SALES_FOOD_TABLE_LIST_REQUEST = "SALES_FOOD_TABLE_LIST_REQUEST";
export const SALES_FOOD_TABLE_SUCCESS = "SALES_FOOD_TABLE_SUCCESS";

// actions for GET company copied from core.
export const REQUEST_GET_CURRENCY = "REQUEST_GET_CURRENCY";
export const SUCCESS_GET_CURRENCY = "SUCCESS_GET_CURRENCY";
export const ERROR_GET_CURRENCY = "ERROR_GET_CURRENCY";
